### ISSUE TITLE
WebSocket framing control

### ISSUE THREAD

**Issue by pgjones** [django/asgiref#100]
Currently ASGI says nothing about WebSocket frames, which is in my view the best approach. However I've been asked about support for this, and I wanted to ask for views about an ASGI extension to allow framing support. Something like,
```
{"type": "websocket.send", "text": "hello", "message_finished": False}
{"type": "websocket.send", "text": "world", "message_finished": True}
```
?

**Comment by tomchristie** [comment]
My first impression would be that we're probably in a phase of "should move slowly". I'm not sure we've got a good sense yet of what implications a proliferation of extensions will have further down the line. And it's not clear to me what critera we should use for determining what makes the cut wrt. new extensions.

*But* this may well just be a case of "I don't need this so I don't want it". 😃

**Comment by tomchristie** [comment]
It would probably be good to start something like this with a clearer use-case motivation. Right now I can only see the issue framed in technical terms. What usage does this allow, and how does it effect the end-user experiance?

**Comment by andrewgodwin** [comment]
The intent of ASGI was specifically to hide the ugliness of WebSocket frames (and PING frames in their entirety) from an application. I'd want to see a good explanation for why it's needed, like @tomchristie says.

**Comment by pgjones** [comment]
I think these are good points, and I also find it hard to think of a use-case motivation, thanks for the discussion. I hope the original requester will add a use-case here otherwise I'll close.

**Comment by pgjones** [comment]
I think this can be closed, lets see if anyone else expresses interest.
