### ISSUE TITLE
ASGI resources list

### ISSUE THREAD

**Issue by florimondmanca** [django/asgiref#110]
Hey!

I'm opening this discussion after originally poking the idea over the [Encode discussion board](https://discuss.encode.io/t/discoverability-of-the-asgi-ecosystem/729/2).

## Context

ASGI has been establishing itself as a common interface enabling interoperability across a whole range of things in the Python async web space, including:

- Apps ([Datasette](https://github.com/simonw/datasette))
- Frameworks (Starlette, and soon Django!)
- Middleware ([sentry-asgi](https://github.com/encode/sentry-asgi), [timing-asgi](https://github.com/steinnes/timing-asgi))
- Wrappers ([mangum](https://github.com/erm/mangum))
- Libraries (this very project)

There are also all sorts of non-code resources out there, like talks and articles.

But, as the ASGI ecosystem is growing, I personally feel like it's hard to keep up on which things are available.

## Listing ASGI resources

In this context, perhaps it could be worth setting up some sort of collaborative list of ASGI resources. This would allow better discoverability and more wide-spread usage of ASGI-related projects, and help getting a grasp of the *scale* of the ecosystem.

It seems a collaboratively-grown static list (e.g. an ASGI [awesome list](https://github.com/sindresorhus/awesome) or an [Are we … yet?](https://wiki.mozilla.org/Areweyet) list) would fill this needs quite well already.

Just to be clear: the ASGI list wouldn't list *any* async resources (the [awesome-asyncio](https://github.com/timofurrer/awesome-asyncio) is already very well suited for that), but only those that are directly related to ASGI, such as those I listed earlier.

## Location

Technically the list *could* be in the ASGI documentation itself, but I feel like the ASGI docs/spec should be part of the list, not the other way around. Giving the list its own space such as a GitHub repo is probably a more sustainable approach.

Digging further into this, maybe now would be a good time to *give ASGI its own space*, e.g. a `python-asgi` GitHub org. I suppose it'd contain this repository and the ASGI list at first (and maybe turn into some sort of umbrella organization for projects?).

Anyway, happy to read everyone's opinion on this. I'd love to help setup the list if this sounds like a good idea at all.

cc @tomchristie, @andrewgodwin, @simonw (who else?)

**Comment by andrewgodwin** [comment]
So, we started a list of ASGI things over at https://asgi.readthedocs.io/en/latest/implementations.html, in the vein of this, but I agree it could maybe be a bit more open/easy-to-edit.

As for the org... while we could move it, asgiref is a core dependency of Django 3.0 and having it under the org lets us keep the security response team the same. I'm not super keen to move it for that reason.

**Comment by tomchristie** [comment]
> As for the org... while we could move it, asgiref is a core dependency of Django 3.0

Personally, I was more wondering if you’d consider splitting ASGI-the-spec (and docs) from the asgiref pypi package.

**Comment by florimondmanca** [comment]
> having it under the org lets us keep the security response team the same.

Yes, makes total sense. :+1:

I thought about it though, and my intuition was, as Tom suggested, that we could perhaps decouple `asgiref` (the reference implementation) from the ASGI spec/docs.

Of course, I'm not the one to make a call here on potential impacts on the workflow between the spec and the implementation. But it seems ASGI (the spec) is quite stable now, and most activity here seems to be focused on  the reference implementation. Looking at the last commit dates on the respective directories seems to support this idea too.

**Comment by florimondmanca** [comment]
https://github.com/florimondmanca/awesome-asgi

**Comment by andrewgodwin** [comment]
I do agree it would be good to separate out the site/docs from the library itself. What would we call the new repo?

**Comment by florimondmanca** [comment]
> What would we call the new repo?

`asgi-spec`? Or even `spec`, as the ASGI prefix would already be in the org name?

**Comment by andrewgodwin** [comment]
Looks like the "asgi" organisation name is already taken, unfortunately. We could also make an `asgi-spec` repo under the Django org, provided I run it past the team first.

**Comment by florimondmanca** [comment]
Thanks for looking into it — what about `python-asgi` for the organization name?

**Comment by andrewgodwin** [comment]
Maybe - I'll have to come back to this in a few weeks as I'm travelling for work and then personal holiday, sorry!

**Comment by Kludex** [comment]
Some years later, I still think the decouple was a good idea.

Now the `typing.py` exists... Which I also don't think it should exist under `asgiref` (https://github.com/django/asgiref/issues/333). Just mentioning because it's relevant in case of this happening.

**Comment by Kludex** [comment]
I still think this is a good idea.

**Comment by Kludex** [comment]
I have bandwidth to make things happen. Is this still wanted?

**Comment by florimondmanca** [comment]
@Kludex What do you reckon should be done about this now?

Today, the list still exists at https://github.com/florimondmanca/awesome-asgi and has been expanding since 2019. I don’t know what folks think about it being under my name, but it’s been manageable. I’d be happy to move it somewhere else we’d feel more appropriate, but where would that be?

Pragmatically, it doesn’t seem like there’s been a need for a new and dedicated “python-asgi” org, so…

**Comment by Kludex** [comment]
Sorry, I didn't mean that part.

The only part I care here is separating the spec documentation, and the package `asgiref` in different repositories.

**Comment by andrewgodwin** [comment]
Unless I stop being the maintainer, I would rather keep them in the same place for now because less things to juggle means less work for me.

**Comment by Kludex** [comment]
> Unless I stop being the maintainer, I would rather keep them in the same place for now because less things to juggle means less work for me.

Hmm... I didn't think about that, sorry.

...then never mind. 👀

**Comment by florimondmanca** [comment]
Alright, then I guess we can close this off? 😃
