### ISSUE TITLE
More language support

### ISSUE THREAD

**Issue by boylegu** [django/asgiref#122]
In other situations I want the RPC server(gRPC with Golang) sends a message to the Django Channel layers(Redis). So `async_to_sync` cannot be used. Please what should I do？

**Comment by andrewgodwin** [comment]
Django Channel layers unfortunately aren't part of the `asgiref` project, so it's not something I can really answer here. They're also not really designed for inter-operability with other languages, like Go, so you may find you need a different message queue layer entirely.
