### ISSUE TITLE
Support naive introspection for wrapped functions

### ISSUE THREAD

**Issue by jcass77** [django/asgiref#136]
It does not seem like the @sync_to_async decorator can currently be used as part of a nested decorator chain.

For example, trying to use the decorator as part of a pytest fixture:

```python
@pytest.fixture
@sync_to_async
def my_test_fixture():
    pass
```

...fails with `AttributeError: 'SyncToAsync' object has no attribute '__name__'`

Aside from testing, this probably limits the range of scenarios that the decorator can be used for in general.

**Comment by andrewgodwin** [comment]
Yup, that was an oversight on my part - thanks for catching it, and for supplying a PR along with the issue!
