### ISSUE TITLE
SyncToAsync/AsyncToSync docstrings incorrect

### ISSUE THREAD

**Issue by graingert** [django/asgiref#139]
AsyncToSync is a"    Utility class which turns an awaitable that only works on the thread with..."

but it takes a `Callable[..., Awaitable[T]]` it doesn't actually accept an `Awaitable[T]`

SyncToAsync is a "Utility class which turns a synchronous callable into an awaitable that
    runs in a threadpool..."

but it takes a `Callable[..., T]` and returns a Coroutine function `Callable[..., Awaitable[T]]` it doesn't actually return an `Awaitable[T]`

**Comment by andrewgodwin** [comment]
The docstrings are not meant to be type specifications, but merely a guideline. I didn't intend for them to be type declarations.

**Comment by graingert** [comment]
No I'm just using `Callable` to make my point clear. A function that returns an awaitable is not itself awaitable

**Comment by andrewgodwin** [comment]
Sure, I get that - if you want to make a pull request to improve the language please do! I'm just saying that they were only written to show which side is synchronous and which is asynchronous, as the AsyncToSync names can be confusing.

**Comment by graingert** [comment]
Ok, can you reopen this issue?
