### ISSUE TITLE
Async generators are not cancelled using async_to_sync

### ISSUE THREAD

**Issue by bjd183** [django/asgiref#145]
I am using aiohttp for a streaming GET request within my Channels/Django project. I retrieve the response with an async iterator and pass events onward using `yield` to create an async generator.

```
async with client.session.get(url) as response:
    async for data in response.content.iter_any():
        yield data
```

If the generator is interrupted (e.g. `break`) without exhausting its contents,

```
async for item in asyncgen():
    if item == myval:
        break
```

then I get the following logging error from asyncio:

>  Task was destroyed but it is pending!
task: <Task pending coro=<<async_generator_athrow without __name__>()>>

I tracked this down to the `async_to_sync` logic that partially mirrors the current asyncio.run() implementation but lacks task cancellation before calling `loop.shutdown_asyncgens()`. I've confirmed for my case that adding that logic no longer generates the error message above.

PR to follow.

asgiref 3.2.3
channels 2.4.0
python 3.7.5 and 3.8.1

**Comment by andrewgodwin** [comment]
Thanks again for leaving such a detailed issue with a PR. Much appreciated!
