### ISSUE TITLE
Is it possibile to call obj.save() inside an event loop?

### ISSUE THREAD

**Issue by bluesurfer** [django/asgiref#147]
In my project, I need to fetch some data from an external API and save it in the database. 

Apparently, `asyncio` is perfect for fetching data but it seems to not play well with Django `save()`.  I know that Django is synchronous but I wonder if this is possible with the help of `asgiref`.

I create this not-working `pytest` toy case

```
import pytest
import asyncio
import random

from django.utils import timezone

@pytest.mark.django_db()
def test_async():
    async def do_something(objs):
        tasks = []
        loop = asyncio.get_event_loop()

        async def fetch(obj):
            """Fetch some data and update the object"""
            await asyncio.sleep(random.choice(range(10)))
            obj.updated = timezone.now()
            await sync_to_async(obj.save)()

        for obj in objs:
            task = loop.create_task(fetch(obj))
            tasks.append(task)
        return await asyncio.gather(*tasks)

    # objs is a list of some model objects
    async_to_sync(do_something)(objs)
```

Unfortunately, it does not work. It gets stuck over the `save` call.

**Comment by bluesurfer** [comment]
Well this is interesting..  this code actually works:
```
@pytest.mark.django_db()
def test_async():
    async def do_something(objs):

        async def fetch(obj):
            """Fetch some data and update the object"""
            await asyncio.sleep(random.choice(range(10)))
            obj.updated = timezone.now()
            obj.save()

        tasks = [fetch(obj) for obj in objs]
        return await asyncio.gather(*tasks)

    event_loop = asyncio.get_event_loop()
    try:
        event_loop.run_until_complete(do_something(objs))
    finally:
        event_loop.close()

```

And... I have no idea why :)

**Comment by carltongibson** [comment]
Do you have a running event loop in the first case?

Look at asyncio.run() to simplify the event loop management in the second.

**Comment by andrewgodwin** [comment]
The first case should have worked - if it didn't that's a bug. The second case will work for older Django versions most of the time, but will mysteriously corrupt itself occasionally - newer Django versions will block you from doing it for this reason.

**Comment by carltongibson** [comment]
The following test added to the Django test suite passes. 

```
diff --git a/tests/async/tests.py b/tests/async/tests.py
index 86ed504c57..6413c24e4b 100644
--- a/tests/async/tests.py
+++ b/tests/async/tests.py
@@ -2,11 +2,11 @@ import os
 import sys
 from unittest import mock, skipIf
 
-from asgiref.sync import async_to_sync
+from asgiref.sync import async_to_sync, sync_to_async
 
 from django.core.cache import DEFAULT_CACHE_ALIAS, caches
 from django.core.exceptions import SynchronousOnlyOperation
-from django.test import SimpleTestCase
+from django.test import SimpleTestCase, TestCase
 from django.utils.asyncio import async_unsafe
 
 from .models import SimpleModel
@@ -63,3 +63,17 @@ class AsyncUnsafeTest(SimpleTestCase):
             self.dangerous_method()
         except SynchronousOnlyOperation:
             self.fail('SynchronousOnlyOperation should not be raised.')
+
+
+class ModelTests(TestCase):
+
+    available_apps = ['async']
+
+    def test_save_can_be_wrapped(self):
+        async def func():
+            obj = SimpleModel(field=1)
+            async_save = sync_to_async(obj.save)
+            await async_save()
+
+        async_to_sync(func)()
+        obj = SimpleModel.objects.get()
```

I think it has the essence of the first example...

**Comment by bluesurfer** [comment]
Let me summarize things up:

## Test 1 - FAIL

Here when I call the `async_save` the test hangs indefinetely.

```
@pytest.mark.django_db()
def test_async_save_not_working():
    async def do_something(objs):
        tasks = []
        loop = asyncio.get_event_loop()

        async def foo(obj):
            async_save = sync_to_async(obj.save)
            await async_save()

        for obj in objs:
            task = loop.create_task(foo(obj))
            tasks.append(task)
        return await asyncio.gather(*tasks)

    # objs is a list of some model objects
    objs = [FooObjectFactory.create() for _ in range(5)]
    async_to_sync(do_something)(objs)
```
## Test 2 -(MILD) SUCCESS

Same as test (1) but with *transaction=True*. It works.. but only under this condition. 

```
@pytest.mark.django_db(transaction=True)
def test_async_save_with_transaction_true():
    async def do_something(objs):
        tasks = []
        loop = asyncio.get_event_loop()

        async def foo(obj):
            async_save = sync_to_async(obj.save)
            await async_save()

        for obj in objs:
            task = loop.create_task(foo(obj))
            tasks.append(task)
        return await asyncio.gather(*tasks)

    # objs is a list of some model objects
    objs = [FooObjectFactory.create() for _ in range(5)]
    async_to_sync(do_something)(objs)
```

## Test 3: SUCCESS

This is the code I am currently using. It does not rely on `asgiref` and seems to work fine. Now, I am actually quite scared by the " mysteriously corrupt itself" sentence by @andrewgodwin 😅 

```
@pytest.mark.django_db()
def test_async_with_asyncio_run():
    async def do_something(objs):
        async def foo(obj):
            obj.save()

        tasks = [foo(obj) for obj in objs]
        return await asyncio.gather(*tasks)

    objs = [FooObjectFactory.create() for _ in range(5)]
    asyncio.run(do_something(objs))
```
## Test 4: SUCCESS

This is the test made by @carltongibson and it works for me too. But, unfortunately, it does not fit my problem.

```
@pytest.mark.django_db()
def test_save_can_be_wrapped():
    async def func():
        obj = FooObject()
        async_save = sync_to_async(obj.save)
        await async_save()

    async_to_sync(func)()
    obj = FooObject.objects.get()
```

## Plot Twist

I am actually including the code from test (3) inside a Celery task. Then, I use `channels` to stream down to the client the updates coming from each "asynchronously" saved objects.
Does Celery somehow save me from the corruption thing? @andrewgodwin  😄 

Because, currently (and surprisingly) everything *seems* to work just fine.

**Comment by andrewgodwin** [comment]
Using celery decreases the risk of corruption, but does not prevent it, sadly.

I'm puzzled as to why test 1 fails and test 3 works, though. Indefinite hanging usually means the event loop is deadlocked on itself or there's a missing `await`.

Channels does ship a `database_sync_to_async` - does that make any difference? It specifically addresses potential deadlocks in the database backend and that might be this.

**Comment by bluesurfer** [comment]
@andrewgodwin I have already tried `database_sync_to_async` and unfortunately it makes no difference.

**Comment by andrewgodwin** [comment]
@bluesurfer Could you try with the most recent version of `asgiref` that I just released? We fixed some potential issues in there - it's unlikely to fix this, but it might.

**Comment by bluesurfer** [comment]
@andrewgodwin nope.. keeps hanging... 

For the record, after weeks of testing (unit test and real test users trying out the app) I decided to deploy in production the idea of test 3 inside a Celery task. 

It still seems to work fine 😅
