### ISSUE TITLE
async_to_sync error when call context is async

### ISSUE THREAD

**Issue by zymergen-stian** [django/asgiref#149]
Similar to #147 , our application wants to send out updates via `django_channels` on db instance `save`. The dilemma is we have calls from both async and sync context:
```py
async def function_1(...):
    await something()
    instance.save()

def function_2(...):
    something_else()
    instance.save()
```

Due to `channel_layer.group_send` is async, we have:
```py
class MyModel(Model):
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        async_to_sync(send_ws)(self)

async def send_ws(instance):
    # do stuff
    await channel_layer.group_send(...)
```

This will error in `function_1`: https://github.com/django/asgiref/blob/master/asgiref/sync.py#L60-L64

We are not able to write `function_1` or `function_2` to be both async or both sync, due to limitations like 3rd party library.

**Comment by zymergen-stian** [comment]
The solution I came up with is as below:
```py
def send_ws_sync(instance):
    try:
        event_loop = asyncio.get_running_loop()
    except RuntimeError:
        # sync, not in a loop
        async_to_sync(send_ws)(instance)
    else:
        # async
        event_loop.create_task(send_ws(instance))
        # not waiting on this to finish, since this func call is blocking the loop
```

Not sure how terrible it is, please comment on any obvious flaws, thank you!

**Comment by andrewgodwin** [comment]
Unfortunately that still won't work - this is a fundamental problem in Python's async design.

You have to design two different API interfaces - one async that you can await, so you can pass it in an async context, and one sync. You can't bundle both into one function because there's no differentiation between sync-call and async-call-to-get-coroutine.

Your solution you linked will technically work I guess  but, as you note, you cannot block on it because you have no async context and so can't `await`.

There's nothing we can do in `asgiref` about this without changes to Python itself, unfortunately, so I have to close this.

**Comment by zymergen-stian** [comment]
I see, thanks for your feedback. A quick say is for my use case, I don't actually need to wait for it to finish. I'm doing a "fire and forget" with that `event_loop.create_task` since it will be ran some time later (usually very soon).

It is quite prevalent in the codebase for a
```
async grandparent --call--> sync parent --call--> async send_ws
```
the middle `sync parent` is 3rd party library (django ORM etc.) that I have no control of. It can get more complicasted with great-grandparent and great-great-grandparent calls, so I have no way to elevate the `send_ws` call everywhere.

**Comment by peteryin21** [comment]
@andrewgodwin @zymergen-stian It sounds like we would need something like this?
```python
async def function_1(...):
    await instance.save_and_publish_async()

def function_2(...):
    instance.save_and_publish_sync()


class MyModel(Model):

    async def save_and_publish_async(self):
	await sync_to_async(self.save())
	await send_ws(self)

    def save_and_publish_sync(self):
        self.save()
	async_to_sync(send_ws(self))


async def send_ws(instance):
	await channel_layer.group_send(...)
```

**Comment by zymergen-stian** [comment]
I don;t think it's practical to create 2 version of the function, since that's basically asking to create both async and sync version of the entire graph of functions that is connected to call this `send_ws`. And it would be impossible to write code since you have to traverse the graph to figure out which of the 2 versions to use at every function call.

Also as mentioned before, when it comes to 3rd party library, e.g. `transitions.StateMachine` https://github.com/pytransitions/transitions, it's not possible to create an async `after_state_change ` to run for each trigger.

**Comment by andrewgodwin** [comment]
I'm just saying that this is a design quirk of Python's async you can't work around; I have many complicated thoughts on it, and have tried to find a reliable way out, but I can't.
