### ISSUE TITLE
Regression in 3.2.6.

### ISSUE THREAD

**Issue by felixxm** [django/asgiref#153]
Version `3.2.6` causes multiple cache-related failures in Django, see [tests failures](https://djangoci.com/job/django-mariadb/170/#showFailuresLink) and [PR with pinned asgiref 3.2.5](https://github.com/django/django/pull/12616).

**Comment by andrewgodwin** [comment]
As we discussed on IRC, I'm looking into it. I suspect the Local instance in CacheHandler is not behaving quite as expected, but I need to trace down why it _did_ work in 3.2.5 (which was way more hacky).

**Comment by felixxm** [comment]
We temporarily pinned asgiref `3.2.5` (https://github.com/django/django/commit/aa21020218a2dcd29a03444ad2a77f03f085b04e), so there is no need to rush. Take your time, thanks!

**Comment by andrewgodwin** [comment]
I traced this down to re-use of memory from old Locals - more details in the commit e4367c571fd1833bda0b7ff0bd68d924916352da.

It's released in 3.2.7, so if you unpin, things should return to normal.

**Comment by felixxm** [comment]
Many thanks :confetti_ball:
