### ISSUE TITLE
Question: Using async_to_sync from a sync inside an async

### ISSUE THREAD

**Issue by animesh-sharama** [django/asgiref#154]
I am trying to use the async_to_sync method in a socket program as below

```
from websockets import WebSocketClientProtocol
from asgiref.sync import async_to_sync

class Player:

    def __init(self, websocket):
      self.websocket = websocket

    @async_to_sync
    async def send(self, msg):
        await self.websocket.send(msg)

    @async_to_sync
    async def receive(self):
         msg = await self.websocket.recv()
         return msg

class Server:
    players = list()

    async def register(self, websocket):
      self.players.append(websocket)
      # register layers and if number of player greater than 2 start the game
      if len(self.players) >= 2:
         Game(self.players[:2]).start_game()
         self.players=self.players[2:]

asyncio.get_event_loop().run_until_complete(
    websockets.serve(Server().ws_handler, 'localhost', 6191))
asyncio.get_event_loop().run_forever()
```

The sync Game code is as below
```
class Game:
  def __init__(self, players):
     self.players = players

  def start_game(self):
     self.players[0].send('hello')
     msg = self.players[0].receive()
```
The issue is whenever I run the server code I get an error RuntimeError: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly, maybe i am doing something really stupid but couldn't understand the error, can someone point the error in my code.

**Comment by andrewgodwin** [comment]
There's not enough code or a traceback here to tell you exactly what you did wrong, but I can tell you the shape you need to look for.

Essentially, what has happened is that, in your case, you have called a synchronous function from an asynchronous function (e.g. `start_game()`), and that is then trying to call something wrapped in `async_to_sync`. That's not possible - you're still in the thread with the async event loop, and in fact you are blocking it by calling that synchronous function, so there's no way we can run an async function for you at that point.

The way to fix it is usually to make all the functions between the `async_to_sync` function async functions themselves, and then you can just `await` the function you were wrapping directly. The traceback you get is usually a good way of identifying this - it'll tell you all the functions in the call stack, and you need to get every single one of them to be async.

This is unfortunately the way of things when you make your main thread asynchronous like you are here. You can't just put synchronous code in the middle of the call stack between two asynchronous code pieces; it has to be either all-synchronous or all-asynchronous all the way down.
