### ISSUE TITLE
Guidance on ASGI extensions

### ISSUE THREAD

**Issue by jordaneremieff** [django/asgiref#169]
I have niche use-case for an ASGI extension, and I'm trying to understand if creating a custom extension is the correct approach. I was going to add a comment to the issue [here](https://github.com/django/asgiref/issues/135) because there is some relevant discussion, but this became rather long and I didn't want to add unnecessary noise to that one.

I'll be referring to my specific use-case and custom extension in this issue, however, my goal is to achieve a broader understanding of how new ASGI extensions should be created and their appropriate level of abstraction which I think might be useful to others as the ecosystem grows and extensions are used more often.

## Background

I'm attempting to implement a publish-subscribe pattern for WebSocket broadcast for a [serverless ASGI adapter](https://github.com/erm/mangum/tree/master/mangum). The limitations of this environment require it to be implemented in a particular way that is different than a normal ASGI protocol server. 

Essentially, a persistent WebSocket connection is established with a client, but the connection scope _must_ be stored in a remote data source to run the ASGI application correctly. The scope is re-used/updated to create a new ASGI application instance for subsequent message events until the connection is closed.

## Extension

I've come at this problem from a few different angles, but the simplest approach I've found so far is to create a custom extension for WebSocket broadcast that is advertised using `websocket.broadcast` as the key with the subscription channels stored in the extra scope information:

```python
"scope": {
    ...
    "extensions": {"websocket.broadcast": {"subscriptions": []}}
}
```

My protocol implementation uses this information to ensure the following:

* Subscriptions in the data source are updated when a new client is subscribed
* New messages are published to subscribers
* Applications are able to unsubscribe clients
* Subscriptions are removed when a connection is closed

There are three events handled by the protocol:

### Subscribe

The protocol server subscribes the current client connection to the channel by adding a connection identifer to the data source and appending it to the `subscriptions` in the scope.

Keys:

type (Unicode string): `"websocket.broadcast.subscribe"`
channel (Unicode string): The name of the subscription channel to subscribe.

### Unsubscribe

The protocol server unsubscribes the current client connection from the channel by removing the subscription from the data source and from the connection scope.

Keys:

type (Unicode string): `"websocket.broadcast.unsubscribe"`
channel (Unicode string): The name of the subscription channel to unsubscribe.

### Publish

Keys:

type (Unicode string): `"websocket.broadcast.publish"`
channel (Unicode string): The name of the channel to publish the message.
body (bytes): The message content.

## Problem

I am developing this against an example Starlette application, which I'll use to demonstrate the problem I'm facing, but my concern is about extension support in ASGI framework implementations generally.

The extension approach requires access to the private `_send` method of Starlette's WebSocket implementation (the public `send` only supports standard WebSocket message events):

```python
async def on_subscribe(self, websocket, message):
    channel = message["channel"]
    await websocket._send(
        {"type": "websocket.broadcast.subscribe", "channel": channel}
    )
```

This seems incorrect and might be confusing to users, my alternative is to implement a middleware for the protocol server and implement it this way in the application:

```python
async def on_subscribe(self, websocket, message) -> None:
    channel = message["channel"]
    await websocket.send_json({"type": "broadcast.subscribe", "channel": channel})
```

Which is more universally applicable across frameworks, but adds a significant amount of complexity to the protocol server.

## Question

I've asked elsewhere and the feedback has been that this isn't the appropriate layer to implement an extension at. The discussion in the issue I mentioned previously seems to echo concerns about how narrowly-defined an extension should be, so I thought it might be good to open a discussion about extensions generally.

My specific questions:

1. Is this the appropriate usage of extensions? 

2. Is there a more generic way to accomodate this case that could also be of use to other ASGI servers? If an ASGI server really wanted to it _could_ implement this extension, though I'm not sure if that'd ever be preferred over something like [broadcaster](https://github.com/encode/broadcaster).

3. Could there be some additional guidance added to the spec/docs about creating new extensions? I'd be happy to PR this myself based on any feedback in this issue, if desired.

**Comment by jordaneremieff** [comment]
Thanks for the reply.

>How much of the other Starlette code do you need to use - header/path handling, etc?

The goal is to adapt the API Gateway WebSocket events in a way that would allow Starlette (or any other application framework) to implement their standard WebSocket behaviour. Since the extension would cause issues here I opted to [rework](https://github.com/jordaneremieff/mangum/pull/125/files#diff-015fd6e0d545c4be4ae0f27cc576feb0R6) the broadcast support into a configurable middleware.

That said, I think broadcast support and the extension itself are separate problems and less important than what you're saying about the protocol itself, so I'm going to shift focus to understand those points.

>you're technically violating the base contract of the protocol (that the connection scope and thus the lifetime of the protocol handler are the same as the lifetime of the socket).

Does the protocol handler necessarily have to persist for the lifetime of the socket?

I may be mistaken, but I had thought that I was technically following the protocol contract by persisting the connection scope and running an application instance for each message event (so long as the relevant socket was still alive). To the application there shouldn't be any noticeable difference between this and a normal WebSocket cycle, so I was considering the protocol handler as an implementation detail.

**Comment by tomchristie** [comment]
Heya @jordaneremieff! In case it's useful, here's a different tack onto broadcast. Feel free to disregard any of it if it's not valuable for what you're trying to do...

With [broadcaster](https://github.com/encode/broadcaster/) I'd also considered using ASGI messaging for sending and receiving broadcast info, but eventually instead opted to take a different direction, and treat "broadcast" as a different kind of [backing service](https://12factor.net/backing-services), and have provide an API onto it, in a similar way to a database, cache, or email service.

I've not ploughed enough time into that area yet, but one potential advantage of taking the "backing service" approach rather than a pure messaging style, is that many broadcast backends provide more than just "listen to what's happening right now", but rather provide a more expansive set of functionality, such as "give me a window of the last X events, and then continue to listen to what's happening after that", or "give me a window onto the period X-Y", which are the kinds of operations that you want to support in order to build, say, a chat room app that retains history. It's more clear to me how you'd go about adding that kind of API to a backing service, than it is how you'd add them into a messaging style.

If you build that in a way that allows for alternate pluggable backends, you still have the benefits of being able to provide a single consistent API, without necessarily exposing too much stuff that's implementation-specific to one particular broadcast service or another.

You might already have explored this avenue, or perhaps it's not relevant to what you're trying to do, but figured it might be useful food for thought?

**Comment by jordaneremieff** [comment]
Thanks @tomchristie!

Broadcaster is really awesome, and the pattern you've implemented there is wonderful. I use this approach [here](https://github.com/jordaneremieff/mangum/blob/f5030eb2edddd3a5507ffa975bbcfd808055c17b/mangum/backends/base.py) to define the common interface for the backend sub-classes, and then configure it [here](https://github.com/jordaneremieff/mangum/blob/f5030eb2edddd3a5507ffa975bbcfd808055c17b/mangum/backends/__init__.py#L75) based on a setting provided. This is necessary for my use-case (with or without broadcast support) because of the requirement to persist the connection scope (ie: regular`websocket.send` events need this as well).

However, since the AWS Lambda environment is stateless the broadcast implementation has to be approached differently. I am unable to use the extended functionality of a particular backend given this limitation, so the design I settled on was to provide only an interface for setting/retrieving the connection identifiers for a particular channel and sending the data to connected clients (which then triggers their next ASGI WebSocket cycle). My intention with the adapter is to provide the bare minimum to establish the necessary messaging interface in this environment and leave up anything more extensive (window history, etc.) to the application.

**Comment by jordaneremieff** [comment]
Thanks again @andrewgodwin for the clarification on extensions, I really appreciate it! I think the initial question that prompted this issue has been answered, so I will not rely on extensions for my use-case. Since I'm sure you have limited bandwidth, I'll summarise my follow-up question and leave this issue for you to close (or continue discussion) as you wish:

Does it violate the ASGI protocol specification for a single WebSocket connection to run multiple protocol handler instances using the same connection scope? If it does, is there specific reasoning behind this?

A clarifying example of my problem could be to contrast it with how Channels 2 might potentially implement multiplexing. In that case, hypothetically, a single protocol handler instance would run an application that manages multiple sub-applications for the lifetime of the WebSocket. In my case, multiple protocol handler instances are created, one for each incoming message, and each handler runs a single application (in a request/response style), for the lifetime of the WebSocket.

**Comment by andrewgodwin** [comment]
I don't think that would violate it - ASGI still follows the design principles laid down in 
Channels, which is that you're free to write multiplexing layers. Note that the scope is specifically called out as immutable once it's passed through a middleware precisely so lower-down apps can do their own things with it.
