### ISSUE TITLE
Excessive use of asgiref.local and sync_to_async breaks other context local implementations

### ISSUE THREAD

**Issue by untitaker** [django/asgiref#170]
I am writing on behalf of my employer, [sentry.io](https://sentry.io).

I am not sure whether this issue should be filed against Django or asgiref. Starting with Django 3.1, signal handlers for `got_request_exception` are executed with the wrong `contextvars` context when running as part of an ASGI request. This can be easily demonstrated by wrapping the Django ASGI app in a middleware that stores something on the context, and trying to retreive that same value from that signal handler.

This is how I became aware of Django's custom context local implementation that is shipped as part of asgiref. I understand why you do the things you do, but consider that this will break a lot of tracing tooling for Python that may only be orthogonal to Django or ASGI. [The situation around context locals is already awful enough](https://docs.sentry.io/platforms/python/contextvars/), it would be terrible if Sentry and tools like it had to implement a codepath specifically for Django 3 applications, or anything that uses asgiref.local.

I can see the following options:

1. avoid releasing Django 3.1 with whatever changes just happened that made errorhandlers execute in the wrong `contextvars` context. Considering that Django 3.1 is already in alpha I would at least consider this as a stopgap measure.
2. modify asgiref.sync_to_async and its inverse to "drive" contextvars if they are available such that contextvars always behave identically to asgiref.local
3. drop asgiref.local entirely and swap it out for the `aiocontextvars` package on PyPI, as the primary purpose of implementing asgiref.local from scratch seemed to have been to support Python 3.6. One would still have to implement 2) for this to work, but the advantage here is that aiocontextvars seems to be significantly more popular across frameworks than asgiref.local.

Those options are not mutually exclusive.

Thanks for considering.

**Comment by MarkusH** [comment]
Without any experience using asgiref or async with Django, and without knowing much about the implementation of either `asgiref.local` or either contextvars implementation, I'd say we should go with `aiocontextvars` for Python 3.6 and the stdlib `contextvars` for Python 3.7 and up. If that's possible, that is.

**Comment by untitaker** [comment]
I think @andrewgodwin and @tomchristie have the most context on this

**Comment by adamchainz** [comment]
asgiref.local is intended to move to contextvars when it supports Python 3.7+, as commented:

https://github.com/django/asgiref/blob/master/asgiref/local.py#L29

`aiocontextvars`' README starts with:

> IMPORTANT: This package will be deprecated after contextvars asyncio backport is fixed. 

And there seems to be some problem with backporting into `contextvars`. I'm not confident in using a library with such a bold warning of deprecation. I know async stuff is moving quickly in Python but we try and support things for the longer term in Django.

**Comment by untitaker** [comment]
Long-term Python 3.6 is dead so I think this problem may solve itself assuming aiocontextvars works for as long as Python 3.6 is popular. It would definetly be a simpler solution than proposal `#2` (setting/resetting contextvars from within sync_to_async if available), but I don't have a strong opinion on this. I only have the high level concern that Django has its own notion of context that nobody else shares.

**Comment by andrewgodwin** [comment]
So, the problem is one of backwards-compatibility. `contextvars` does not provide quite the same interface as `threading.Local` did; I tried to port things to using only `contextvars` but this would basically make it impossible to sensibly call most of the Django APIs across the sync/async boundary, as well as ruining backwards-compatible behaviour expected of connections and other local-backed items by synchronous middleware.

Specifically, Django's ability to run a request context partially in a fresh sync thread, partially in an existing sync thread that is reserved by thread_sensitive, and partially in an async thread is not something I could get contextvars to solve. It's possible I didn't stare at the problem long enough, but I did spend six months trying to get everything to work. If we wanted to rewrite half of Django core and break backwards compat we could definitely do it, but that is, of course, not going to happen.

Going back to your original problem - we should be preserving the outside `contextvars` context from within any sync_to_async / async_to_sync calls, so I'd consider that a bug we can fix. My general goal here is to have Django treat contextvars pretty normally (passing the context around between threads, obviously, but in the way the python module tells you to) and only have to really mess with the threading-style API.

**Comment by untitaker** [comment]
Thanks. I just looked and found the corresponding tests in asgiref for contextvars so I am not really sure what the issue is then. I'll take a deeper look.

**Comment by andrewgodwin** [comment]
The contextvars support was added later on, so it's quite possible it is not fully baked, but if we can fix it I'll turn a release around stat (this is one nice thing about asgiref being separate to Django).

**Comment by untitaker** [comment]
Fixed in #171, can verify that with this change the behavior disappears. I am absolutely not sure if the patch is efficient but I could not find a better way to let a random awaitable run in a particular context.

**Comment by untitaker** [comment]
thanks, would it be possible to bump asgiref and set a minimum required version in Django 3.1?

**Comment by andrewgodwin** [comment]
asgiref is already bumped to `3.2.8`; Django 3.1's requirement will automatically bring this in as it's set to `>= 3.2`. We should probably modify that requirement to be `~= 3.2` so there's a chance to release a backwards-incompatible 4.0 eventually, but either way any pip client that's talking to PyPI will bring in this version.

**Comment by untitaker** [comment]
django 3.0 [requires `~= 3.2`](https://github.com/django/django/blob/44da7abda848f05caaed74f6a749038c87dedfda/setup.py#L86) so if people who were to upgrade to Django 3.1, they would *possibly* stay on asgiref 3.2.7 due to dependency pinning.

Thanks for bumping!±

**Comment by andrewgodwin** [comment]
I know, we'll have to work it out on the Django side. I'm tempted to change the requirement to include a `~=3.2` and a `>=3.2.8`.

**Comment by andrewgodwin** [comment]
Unfortunately this is not closed, as the patch doesn't pass Django's test suite, there's 8 failures (https://djangoci.com/job/pull-requests-bionic/6535/database=sqlite3,label=bionic-pr,python=python3.7/). I'm currently trying to work out why, but if I can't figure it out in a day or two I'll have to revert the change for now so Django master continues working without a pinned version.

**Comment by andrewgodwin** [comment]
(also this might encourage me to finally put the Django test suite as part of tests for asgiref on here)

**Comment by andrewgodwin** [comment]
OK, it appears that `_awaitable_with_context` is somehow screwing up exceptions; removing the use of it makes Django's test suite pass again.

@untitaker Any ideas? I might just revert this until we can get Django passing. I also can't get the tests you wrote to run on my machine to pass even on asgiref `master`, so I'm worried they're too fragile.

**Comment by untitaker** [comment]
I will look into this tomorrow. That is very odd, those tests have been passing very reliably for me (osx)

**Comment by andrewgodwin** [comment]
Yeah, I'm on Linux + Python 3.8, but so is Travis and they passed there, which is confusing.

**Comment by andrewgodwin** [comment]
Nevermind, I was testing the wrong branch. Your asgiref tests run fine here, it's just the Django ones that break.

**Comment by felixxm** [comment]
Also at the end of tests we have many `TypeError`'s:
```
Traceback (most recent call last):
  File "python3.7/tests/.env/lib/python3.7/site-packages/asgiref/local.py", line 90, in __del__
  File "python3.7/tests/.env/lib/python3.7/_weakrefset.py", line 59, in __iter__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Local.__del__ at 0x7f82ea911290>
```

**Comment by untitaker** [comment]
@andrewgodwin I would revert and release asgiref until we find the issue, otherwise Django stable is broken.

**Comment by andrewgodwin** [comment]
@untitaker The nature of the bug made it unlikely any 3.0 users would run into it, which is why I was OK waiting a day (I also ran out of personal coding time yesterday to do it in). Your new fix looks good; it's out in `3.2.9` and passes Django tests locally and on your machine, so we'll get core Django to unpin and check.

**Comment by felixxm** [comment]
Issue described in this [comment](https://github.com/django/asgiref/issues/170#issuecomment-644519656) still exists on Python 3.7+. The easiest way to reproduce it is to create a new project and quit the server with `CTRL-C`, e.g.
```
$ pip install Django==3.1b1
$ pip install asgiref==3.2.9
$ django-admin startproject test_project
$ cd test_project
$ python manage.py runserver
CTRL-C
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 18, 2020 - 07:06:46
Django version 3.2, using settings 'ticket_31670.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^CException ignored in: <function Local.__del__ at 0x7f2fcc94e680>
Traceback (most recent call last):
  File "lib/python3.7/site-packages/asgiref/local.py", line 90, in __del__
  File "lib/python3.7/_weakrefset.py", line 59, in __iter__
TypeError: 'NoneType' object is not callable
```

**Comment by felixxm** [comment]
See also [CI logs](https://djangoci.com/job/django-master/database=sqlite3,label=bionic,python=python3.7/lastCompletedBuild/consoleFull).

**Comment by untitaker** [comment]
@felixxm I think that issue was introduced in edd0570, unrelated to this patch. I will create a fix.

**Comment by felixxm** [comment]
@untitaker Thanks :+1: Yes it's also in `asgiref==3.2.8`.
