### ISSUE TITLE
"HTTP handshake"?

### ISSUE THREAD

**Issue by adamhooper** [django/asgiref#177]
On https://asgi.readthedocs.io/en/latest/specs/www.html

> The connection scope information passed in scope contains initial connection metadata (mostly from the HTTP handshake):

I think "HTTP handshake" is unclear. I searched [all the HTTP-related RFCs I could find](https://developer.mozilla.org/en-US/docs/Web/HTTP/Resources_and_specifications), and "handshake" is only described as "TLS handshake" or "Websockets handshake".

**Comment by andrewgodwin** [comment]
Good point, I'll correct it to remove "handshake". I suspect that description was pulled over from the websocket part subconciously.
