### ISSUE TITLE
Question: What is an ASGI Middleware allowed to "store" in the scope?

### ISSUE THREAD

**Issue by sm-Fifteen** [django/asgiref#178]
Altering the connection scope is one of the main ways ASGI middlewares have to affect the behavior of the applications downstream to them (although not all of them make sure to copy the dict before modifying it [like the spec advises](https://asgi.readthedocs.io/en/latest/specs/main.html#middleware)). The ASGI spec itself doesn't really make any mention of what is allowed to be stored inside the scope (or even if the middlewares are allowed to create their own keys), although it does [limit what can be stored inside events](https://asgi.readthedocs.io/en/latest/specs/main.html#events) to types that can safely be encoded in JSON.

I have seen middlewares that try to save more complex objects in the scope, be it objects implementing various methods and protocols that may be relied upon by an application downstream (which would be lost if serialized and deserialized) or outright non-serializable resources like database connections (and possibly file handles). Given that the spec makes no mention of such restrictions, should ASGI middleware be allowed to store these objects in the connection scope? Should they be limited to storing anything in the extensions section only?

**Comment by andrewgodwin** [comment]
Honestly, I never really dived too much into specifying this as at the end of the day middleware can, and will, put anything in there. I think the only restriction I'd personally advice is not mutating anything that exists or using a key that is part of the normal ASGI spec; I think it's fine, though, to put arbitrary other data at the top level if it's namespaced pretty obviously, especially if you're just writing the middleware for your own purposes.

Putting non-serializable objects in there is... a choice, but again, I don't think this would benefit from a hard-and-fast rule.

**Comment by sm-Fifteen** [comment]
That's fair, a spec only has power as far as its implementations are willing to follow it, at the end of the day. I figured an "extensions-only" rule would make sense, given how a middleware, by definition, "plays the role of both server and application" and would therefore have to follow the same rules in regards to "server"-specific information.

At any rate, thanks for clarifying this.

**Comment by andrewgodwin** [comment]
Totally - I would heartily encourage middleware to stick to putting things in `extensions` and only using serializable types as much as possible... but, I'm not going to lose sleep if people go their own way :)

Your point about playing both server and application is spot on, though. I like that framing of it.

**Comment by tomchristie** [comment]
Voicing for one part of the ecosystem: I certainly wouldn't be averse to Starlette moving towards using "extensions" for any non-standard stuff bits of middleware add in. Don't really recall what the situation was when it started *not* always doing that, but likely more of an evolutionary thing. (Eg. "extensions" might not have existed as a formalised key while I was trying to develop a middleware pattern for Starlette.)
