### ISSUE TITLE
ASGI_THREADS setting does not persist

### ISSUE THREAD

**Issue by oTree-org** [django/asgiref#179]
ASGI_THREADS is used to instantiate an executor at the class level in SyncToAsync:

    # If they've set ASGI_THREADS, update the default asyncio executor for now
    if "ASGI_THREADS" in os.environ:
        loop = asyncio.get_event_loop()
        loop.set_default_executor(
            ThreadPoolExecutor(max_workers=int(os.environ["ASGI_THREADS"]))
        )

However, this executor is deleted as soon as AsyncToSync._run_event_loop() finishes, since it calls `loop.close()` (see asyncio/base_events.py):

    def close(self):
        [...]
        executor = self._default_executor
        if executor is not None:
            self._default_executor = None
            executor.shutdown(wait=False)

The next time loop.run_in_executor() is run, it falls back to creating a new ThreadPoolExecutor() that does not know about ASGI_THREADS:

    def run_in_executor(self, executor, func, *args):
        ...
        if executor is None:
            executor = self._default_executor
            if executor is None:
                executor = concurrent.futures.ThreadPoolExecutor()
                self._default_executor = executor
        return futures.wrap_future(
            executor.submit(func, *args), loop=self)

I don't know much about asyncio/ASGI, but when I test with Django channels I see it closes event loops frequently, like every few page loads. I can get it running single threaded by persisting the executor on SyncToAsync instead of using set_default_executor:

```
if 'ASGI_THREADS' in os.environ:
        default_thread_executor = ThreadPoolExecutor(max_workers=int(os.environ["ASGI_THREADS"]))
    else:
        default_thread_executor = None # use default
```

Then:

    async def __call__(self, *args, **kwargs):
        loop = asyncio.get_event_loop()

        if self._thread_sensitive:
            if hasattr(AsyncToSync.executors, "current"):
                # If we have a parent sync thread above somewhere, use that
                executor = AsyncToSync.executors.current
            else:
                # Otherwise, we run it in a fixed single thread
                executor = self.single_thread_executor
        else:
            executor = self.default_thread_executor

Sorry if I misunderstood anything.

**Comment by carltongibson** [comment]
It's Sunday so, I need to dig into this to check but, I wonder if this is a symptom of https://github.com/django/daphne/issues/319. 

@oTree-org You're editing SyncToAsync? Are you on Python 3.7+? If so could you try using `get_running_loop()` in place of the `loop = asyncio.get_event_loop()` that you have in the first quoted block above? 

(Summary: we're passing twisted a custom loop, in order to allow it to work under Django's auto-reloader, but `get_event_loop()` returns the default event loop for the current thread, which without a `set_event_loop()` call isn't necessarily the running loop. `get_running_loop()` is the preferred API but is 3.7+.)

**Comment by oTree-org** [comment]
Thank you for the reply. I am indeed editing SyncToAsync manually, on Python 3.8. I made that suggested change, but I get this error on runserver:

```
Traceback (most recent call last):
  File "c:\otree\core\otree_startup\__init__.py", line 213, in do_django_setup
    django.setup()
[...]
  File "c:\otree\core\otree\channels\utils.py", line 2, in <module>
    from asgiref.sync import async_to_sync
  File "c:\otree\ve38\lib\site-packages\asgiref\sync.py", line 189, in <module>
    class SyncToAsync:
  File "c:\otree\ve38\lib\site-packages\asgiref\sync.py", line 209, in SyncToAsync
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop
```

I guess this happens because the `if "ASGI_THREADS" in os.environ:` code is directly on the class, not inside any method, so it gets executed as soon as the module is imported, before daphne starts running?

Anyway, I took a look at the issue you linked. I can't tell whether they are caused by the same underlying issue. Downgrading to Daphne 2.4.0 does make the problem go away for me (though 2.4.0 seems to have other bugs that prevent me from using it in production).

Thank you and let me know if I can provide any more details or make a PR.

**Comment by carltongibson** [comment]
Well, not 100% sure it’s the same issue from what you say but, the Daphne issue is the one I’d like to resolve... 

(Not sure yet what the solution is: we probably do need to revert the original change, but that leaves us without the Django auto reloader compat...) Happy to talk on the issue there.

**Comment by andrewgodwin** [comment]
I'm not sure this is an `asgiref` problem - `loop.close()` appears to only be called inside `_run_event_loop`, which is only ever called with a new loop. I can dig further into it if you're sure it's in asgiref, but it may well be Daphne leaking over if you're using that, as @carltongibson suggests.

**Comment by oTree-org** [comment]
Thank you both. I am OK with closing this issue.

**Comment by carltongibson** [comment]
Ok, let’s close here and discuss on Daphne. (We can always come back.). Thanks both.

**Comment by variable** [comment]
> Thank you for the reply. I am indeed editing SyncToAsync manually, on Python 3.8. I made that suggested change, but I get this error on runserver:
> 
> ```
> Traceback (most recent call last):
>   File "c:\otree\core\otree_startup\__init__.py", line 213, in do_django_setup
>     django.setup()
> [...]
>   File "c:\otree\core\otree\channels\utils.py", line 2, in <module>
>     from asgiref.sync import async_to_sync
>   File "c:\otree\ve38\lib\site-packages\asgiref\sync.py", line 189, in <module>
>     class SyncToAsync:
>   File "c:\otree\ve38\lib\site-packages\asgiref\sync.py", line 209, in SyncToAsync
>     loop = asyncio.get_running_loop()
> RuntimeError: no running event loop
> ```
> 
> I guess this happens because the `if "ASGI_THREADS" in os.environ:` code is directly on the class, not inside any method, so it gets executed as soon as the module is imported, before daphne starts running?
> 
> Anyway, I took a look at the issue you linked. I can't tell whether they are caused by the same underlying issue. Downgrading to Daphne 2.4.0 does make the problem go away for me (though 2.4.0 seems to have other bugs that prevent me from using it in production).
> 
> Thank you and let me know if I can provide any more details or make a PR.

Hello I am facing this problem https://stackoverflow.com/questions/68993061/daphne-channel-v3-deployment-runtimeerror-no-running-event-loop I am curious if you have a solution?
