### ISSUE TITLE
Pub/sub extensions?

### ISSUE THREAD

**Issue by alexhultman** [django/asgiref#180]
Hello and sorry if I'm misusing this issue tracker,

I did a quick search for pub/sub and found this closed issue:

https://github.com/django/asgiref/issues/169

I don't really understand how things work though - is there any such broadcast support or is it entirely non-standard?

The thing is, I have a server that is crazily optimized for doing pub/sub efficiently - exposing that support to the "framework" above would unlock really important performance characteristics to Python "frameworks" using ASGI.

Imagine you have some data you want to publish to a million subscribers - now that could be one single call from Python to the underlying implementation to be efficiently handled. This, vs. having the "framework" implement that in script, and obviously not as optimized.

Adding official pub/sub features like subscribe(channel), publish(channel, message), unsubscribe(channel), unsubscribeAll(), subscriptions(), etc - is there any progress on doing so? Are there any non-standard extensions currently in use?

I'm planning to (maybe) expose this server via ASGI, but that really requires these extensions, otherwise it's not worth it, as performance would be entirely lost in script.

**Comment by andrewgodwin** [comment]
There's no progress on doing this as part of the core ASGI spec, I don't expect it will just happen - if you are interested in doing it, I would suggest you write an extension specification, and then get at least one other similar project to agree to it (or just have your extension and make sure it's easy for apps to use).

I'd love to see pub/sub be possible - after all, that was the basis behind Channels 1 - but I also don't want to design it in a vacuum which is why I've not since taken a stab at it!

**Comment by alexhultman** [comment]
Sounds perfectly sane. What I would do is implement it, then "market" the non-standard extension using benchmarks then hopefully get these frameworks to support it.

It's risky, I already had this server ship as the default WebSocket implementation in Socket.IO for a few versions but since Socket.IO implements their own pub/sub layer in very naive script, with tons of layers, overall performance was still really bad.

If I get this thing integrated with Python I would like to work with some framework to enable this extension before it goes public.

**Comment by jordaneremieff** [comment]
@alexhultman have you considered the backing-service approach described in this comment https://github.com/django/asgiref/issues/169#issuecomment-638853256?

**Comment by alexhultman** [comment]
I considered this a project for a while, but after looking into it a bit more I've decided to not continue working on it.

The idea to have pub/sub as part of ASGI is still valid, but I won't be doing it.
