### ISSUE TITLE
Proposal: "http.response.sendfile" extension.

### ISSUE THREAD

**Issue by abersheeran** [django/asgiref#184]
Add the sendfile extension to allow ASGI programs to return response through `sendfile`.

In `scope`:

```python
"scope": {
    ...
    "extensions": {
        "http.response.sendfile": {},
    },
}
```

Response:

```python
await send({"type": "http.response.start", ...})
await send({"type": "http.response.sendfile", "file": file-obj})
```

Some related links:

https://docs.python.org/3.7/library/asyncio-eventloop.html#asyncio.loop.sendfile
https://github.com/encode/uvicorn/issues/35

**Comment by andrewgodwin** [comment]
Yes, I can see this being sensible, since having it as an extension means that things not on (a new enough) asyncio can just not provide it.

**Comment by abersheeran** [comment]
Can I submit a PR to add this section to the ASGI document?

**Comment by andrewgodwin** [comment]
Totally - I think it's best to iterate on a draft here, so we can make sure the specification is nailed down properly.

**Comment by abersheeran** [comment]
Okay.

**Comment by davidism** [comment]
It seems like this isn't (directly) related to `X-SendFile` in httpd/lighttpd and `X-Accel-Redirect` in Nginx. Those set headers pointing to a path (SendFile) or internal URI (Accel) that tell the reverse proxy to do the sendfile call.

The extension should make it clear that these aren't the same. Or maybe it would be possible to accommodate them along with allowing the ASGI server to use `loop.sendfile`.

**Comment by andrewgodwin** [comment]
Yeah, we need to make this very clear in terms of what it does and allows. Maybe a rename to make it clearer - something like `http.response.direct-file-stream`.

**Comment by abersheeran** [comment]
All right. If the name isn't clear enough, we can consider using zero-copy. That's what this extension is all about. What do you think?

**Comment by andrewgodwin** [comment]
I'd be OK with `zero-copy`, that seems reasonable, though maybe `zero-copy-send` to be a bit more precise?

**Comment by synodriver** [comment]
Hi, I'm trying to implement this extension in hypercorn, but hava some question about it. The [document](https://asgi.readthedocs.io/en/latest/extensions.html) said file is an integer, while ```loop.sendfile``` accepts only file object. I'm using ```os.fdopen``` in this case, however, that just make more trouble. Here is my [code](https://gitlab.com/synodriver/hypercorn/-/blob/zerocopy/src/hypercorn/asyncio/tcp_server.py#L106) that did not work. Can you give me some advice?

**Comment by abersheeran** [comment]
[`loop.sendfile`](https://docs.python.org/zh-cn/3/library/asyncio-eventloop.html#asyncio.loop.sendfile) just wraps [`os.sendfile`](https://docs.python.org/zh-cn/3/library/os.html#os.sendfile).

**Comment by abersheeran** [comment]
@synodriver Maybe the PR https://github.com/encode/uvicorn/pull/1210 can help you.
