### ISSUE TITLE
Migration from wsgi to asgi questions

### ISSUE THREAD

**Issue by AlwxSin** [django/asgiref#186]
We have a django app running on gunicorn with eventlet workers. But we are not satisfied with eventlet cause it monkeypatches everything and works badly with tooling. So we decided to move to asgi. 
* I replaced gunicorn eventlet worker with UvicornWorker
* I replaced `threading.local` usage with `asgi.Local`
* For [cachetools](https://github.com/tkem/cachetools/) we need to use `threading.RLock` because `cachetools` is not threadsafe

And after that, we ran a load test. Seems like with the asgi server we lost about 30% of performance.

So, questions are:
* Are there any guides/docs where I can find how to tune asgi server? Anything about performance?
* Are there any docs that describe how asgi works with django? I'm not sure but looks like there is main asyncio loop and for each request, asgi runs separate thread (and it looks like I must make `async_to_sync` functions that do network requests)
* Is it safe/needed to use `threading.RLock` inside sync code or should I replace it with something?
* Should I use `asgi.Local(thread_critical=True)` or `asgi.Local()` and how `thread_critical` works with different code?

**Comment by abersheeran** [comment]
Since Django's ORM and other IO operations are all blocking IO, they can only be executed in a thread pool in asynchronous code, which is not efficient.
At this stage, perhaps monkey patches such as `gevent` are more suitable for accelerating Django projects.

**Comment by carltongibson** [comment]
Hi, sorry to be a pain but, this isn't really an issue... — Can I please direct you to the Forum, where discussion topics are more appropriate. 

https://forum.djangoproject.com

Thanks.

**Comment by AlwxSin** [comment]
@carltongibson I will go to the forum with some questions, thanks. But question about performance is suitable here as I think, it's important.

**Comment by carltongibson** [comment]
Hi, yes. It's a good question. 

But still the issue tracker is not the best place to begin a discussion. It's not yet an addressable issue. 

As the initial reply shows, I suspect it'll go off in all number of pathways before we come to something concrete.

I hope that makes sense. (It's a fairly standard policy in my experience.)

**Comment by allen-munsch** [comment]
@AlwxSin were you able to determine how to get good enough performance? I originally looked into using ASGI and mounting WSGI, and found huge performance issues.

I'm thinking of going the route of using WSGI, and mounting ASGI ... that way all of the legacy/core code that was monkeypatched should operate at about the same.

Using something like:

- https://github.com/allen-munsch/benchmark-django-fastapi/blob/main/testdjango/wsgi_with_slow_api_mounted.py

**Comment by AlwxSin** [comment]
@allen-munsch No, we returned to gevent ¯\_(ツ)_/¯

**Comment by allen-munsch** [comment]
@AlwxSin That is what we are doing as well. Although upgrading to django3.2, and py3.8.10 had it's own issues. With the recent breaking changes on eventlet 0.31

gonna have to test it out, but I think the werkzeug DispatcherMiddleware approach should be feasible without the dramatic performance impact.

My concern at the moment is how the `sync_to_async` executor will fair. Since it uses a ThreadPoolExecutor

Thanks for the quick response.
Cheers
