### ISSUE TITLE
Proposal: Add Client Certificate to Scope

### ISSUE THREAD

**Issue by mdgilene** [django/asgiref#187]
# Background
When running an application using SSL it is often the case that the server will request client certificates (especially in corporate environments) and validate them against a specified authority. But only accounts for the "authentication" portion of the security process. We are still missing the "authorization" step. With the curent ASGI spec there is no definition for providing the client certificate sent with the request to the underlying application for further authorization purposes.

# Proposal
Add `client_cert` to `scope`

```python
"scope": {
    ...
    "client_cert": ...
}
```

The format for the client certificate is up in the air for me and I would be looking for input on what format others think is best here, but there are 2 main options I see:

1. Binary Format
2. Dictionary

Both of these can be provided by [ssl.SSLSocket.getpeercert](https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.getpeercert) by specifying the `binary_form` flag.

I am also open to different names for the additional `scope` key. I chose `client_cert` because that is how I think of it. But maybe there is a more standard name.

# Related Links
https://github.com/encode/uvicorn/issues/745

**Comment by andrewgodwin** [comment]
So, we're actually already talking about this over in #112 - there was an effort to spec out how this should look, but it never quite got to a concrete proposal. I think it makes sense to have an extension for client certs/SSL info, but making it into an actual, proper specification is the hard part, I think.

I'm gonna close this in favour of the other ticket - if you want to continue the discussion there, that'd be great.

**Comment by mdgilene** [comment]
@andrewgodwin I apologize I did not see this discussion previously. I was pretty laser focused on the client certificate portion due to my current needs however, providing access to the transport as a whole is a more generalized solution that accomplishes what I am looking for as well. Thanks!
