### ISSUE TITLE
Scope["client"] with WSGI

### ISSUE THREAD

**Issue by abersheeran** [django/asgiref#203]
In https://asgi.readthedocs.io/en/latest/specs/www.html#wsgi-compatibility

> REMOTE_HOST/REMOTE_ADDR and REMOTE_PORT are in client

But in https://github.com/abersheeran/a2wsgi/pull/6, sralloza asked such a question:

> What if REMOTE_ADDR is present but REMOTE_PORT isn't? Or vice versa?

The ASGI documentation does not seem to tell this. Set to None or?

**Comment by andrewgodwin** [comment]
Good point - as written, the ASGI spec only allows either the whole thing to be `None`, or a tuple of two values. I'd say, for compatibility reasons, if either value is missing, `client` should not be populated, until if/when we allow `None` inside the tuple as part of the main spec.

**Comment by abersheeran** [comment]
Thanks for your quick reply. By the way, can I add [a2wsgi](https://github.com/abersheeran/a2wsgi) to [asgi Implementations](https://asgi.readthedocs.io/en/latest/implementations.html)? If so, which category should I add it to?

**Comment by andrewgodwin** [comment]
Yup, go ahead - choose whatever category you think is best, or add a new one if you like. Just submit a PR.
