### ISSUE TITLE
version 3.3.0 hang problem

### ISSUE THREAD

**Issue by belongwqz** [django/asgiref#205]
When I upgrade from version 3.2.10 to 3.3.0(`daphne:2.5.0, python:3.8.2, django:2.2.16`), the server looks like hang there randomly,  no error info found in `access.log` and `asgi.log`.

the `supervisord.conf` as follow:
```
[fcgi-program:om]
directory=./
socket=tcp://0.0.0.0:8000
command=daphne -u ./daphne%(process_num)d.sock --fd 0 --access-log ./logs/access.log --proxy-headers MyProject.asgi:application
numprocs=4
process_name=asgi%(process_num)d
stdout_logfile=./logs/asgi.log
redirect_stderr=true
```

Now, I downgrade to 3.2.10, everything is OK.

Maybe modification about thread has some bugs or something I should do to adapt it.

**Comment by andrewgodwin** [comment]
I'll need a lot more than this for a bug report, unfortunately - at minimum, a small, simple code example that reproduces the problem. I can't just go off of a supervisor config, since it gives no information at all.

**Comment by dacevedo12** [comment]
I'm experiencing something similar to what's being described here. Some functions using async_to_sync hang the server during a few minutes

It all seems to have started with asgiref 3.3.0

**Comment by andrewgodwin** [comment]
Are you able to give me a small, reproduceable example? I can definitely believe this is caused by us defaulting `thread_sensitive` to `True` in that release, but I need something to reproduce it, since our test cases all pass right now.

**Comment by dacevedo12** [comment]
Thanks for your quick response Andrew,

Unfortunately, I haven't managed to reproduce the problem. This only seems to happen under heavy load which makes it tough to catch.

The current stack is: Django Channels + ASGI -> Django 3.0 with views using the @async_to_sync decorator

I'll update if I discover something useful

**Comment by andrewgodwin** [comment]
Thanks. These types of problems do manifest like that, unfortunately - it's quite possibly something specifically in Channels, since that has its own set of async near-magic that meets asgiref's.

**Comment by dacevedo12** [comment]
Just wanted to confirm that after downgrading to 3.2.10 the problem disappeared :tada:

**Comment by bjd183** [comment]
I experienced a similar issue that, unfortunately, is difficult to reproduce in a simple test case. I was able to track the behavior to my attempts to keep an lightweight async service in-process during tests rather than out-of-process as in production. When I moved the service to a subprocess, the issue was resolved.

**Comment by LostInDarkMath** [comment]
I run into the same problem. But I'm not able to reproduce this :/ 

Downgrading to 3.2.10 solved the problem for me too :+1:

**Comment by andrewgodwin** [comment]
Yeah, it's likely there's some edge case of using async that this is exposing, but unfortunately until we can get a reproduceable test case I can't tell what it is. I've already been through the code and checked everything _looks_ alright, there's not a whole lot more I can do alone.

**Comment by belongwqz** [comment]
So sad this problem has not been solved and the reason has not been found, and version 3.3.x was force required on django 3.2.x.As my project is relatively large, I cannot upload all the code due to commercial reasons. I try to reproduce the problem with a small amount of code, but no success. Maybe the error log from daphne can do some help:
```
2021-xx-xx 14:10:35,972 WARNING  Application instance <Task pending name='Task-70' coro=<ProtocolTypeRouter.__call__() running at
    /path/python3.8/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at
    /path/python3.8/asyncio/futures.py:360, <TaskWakeupMethWrapper object at 0x7f4f0ee2a730>()]>> for connection <WebRequest at 0x7f4f0ef232b0 method=GET uri=/ok clientproto=HTTP/1.1>
    took too long to shut down and was killed.
```
If this problem cannot be located and resolved in the short term, how we can switch to configure thread_sensitive to False in order to avoid the problem and upgrade to django 3.2?

**Comment by belongwqz** [comment]
> Ah, you're using Channels, you didn't mention that initially - you might want to go look at issues over there, as it's significantly more complex and a lot easier to deadlock yourself/write async code wrong.
> 
> If you're running into this error, I will caution you that it is probably an early warning of an existing deadlock or race condition that was already in your code, so the best thing to do would be to track it down (via PYTHONASYNCIODEBUG, bisecting code, etc.) before it crops up on real user data.
> 
> There's no core workaround for this reason - again, if you can somehow make it happen in a small sample, I can help work out why, but the fact you can't implies it's probably a bug in how the app is written at large.
> 
> The one way we have of modifying how SyncToAsync does its threading is the `thread_sensitive_context` attribute on the class, which you can overwrite with your own way of detecting contexts if you wish (it needs to be something with a `get()` method, and look vaguely like a ContextVar), so if you want to pursue that road, you can.

@andrewgodwin Thank you for your patience, maybe something related to these two issues in https://github.com/django/channels/issues/1576 and https://github.com/django/channels/issues/1491.

looks like there is a problem with the combination of channels3(asgiref3.3.x)+django3.

I'll try to reproduce it in a minimal sample project.

**Comment by michelangelomo** [comment]
Hello everyone, any update on this?

**Comment by belongwqz** [comment]
At last, I use uvicorn instead of daphne, this problem is magically solved.
before `daphne xxx.asgi.application`, after `uvicorn xxx.asgi.application`.
So I suspect it has something to do with daphne. 
However, due to the large size of my project, code examples cannot be provided.

**Comment by belongwqz** [comment]
By debug with log, I got this:
```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
	debug_error_string = "{"created":"@1642484996.785116691","description":"Error received from peer ipv4:xxxip:xxxport","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Exception iterating responses: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","grpc_status":2}"
>
```

I use grpc with stream message between django and other grpc server, I guess the grpc stream message will block in one thread, before asgiref 3.3.0, different stream message communication in different processes, after asgiref 3.3.0 when the thread blocked by grpc stream message, the django application hung with it.

when I limit the time (use functimeout library) of grpc stream message communication function like this:

```
@timeout(10)
def get_grpc_stream_messae_api(request): // this is a django api view function
    grpc stream message communication logic here
```

when I call this api frequently, then the django application will good but the `get_grpc_stream_messae` rase a timeout exception. Does this mean that asyncio can't handle the blocking problem?

If so, what's the right way to solve this problem here? how I set thread_sensitive to False when use asgiref new version?
