### ISSUE TITLE
TypeError: object SyncToAsync can't be used in await expression

### ISSUE THREAD

**Issue by valentinogagliardi** [django/asgiref#206]
Hi there. Thanks for the wonderful effort on bringing async to Django. Wondering if I'm doing something wrong here:

```python
def _get_stuff():
    return Blog.objects.first()


async def index(request):
    result = await sync_to_async(_get_stuff)
    print(result.title)
    return JsonResponse({"msg": "hi"})
```

When I call this view I get `TypeError: object SyncToAsync can't be used in 'await' expression`. Since it's not mentioned in the documentation I discovered just by chance that I need parenthesis after the call to `sync_to_async`. So this works:

```python
def _get_stuff():
    return Blog.objects.first()


async def index(request):
    result = await sync_to_async(_get_stuff)()
    print(result.title)
    return JsonResponse({"msg": "hi"})
```

**Comment by carltongibson** [comment]
Hi @valentinogagliardi 👋 This is expected... So... 

You can `await` a coroutine. 

`sync_to_aync` returns a callable, that when you call it will return one of said coroutines which can then be awaited. 

That sounds like a mouthful. Did it make sense? 

(I'm going to close this, as it's not really an issue... — The [Django Forum](forum.djangoproject.com) is a good place for usage questions.)
