### ISSUE TITLE
Has StatelessServer been updated to the ASGI 3.0 spec? 

### ISSUE THREAD

**Issue by davidmarquis** [django/asgiref#209]
I'm currently trying to upgrade my app from Channels 2.4.0 to Channels 3.0.0 and I'm having issues with running my worker.

After some investigation, I'm under the impression that the `StatelessServer` provided in `asgiref` hasn't been updated to the new Application specifications in ASGI 3.0.

Part of StatelessServer that is trying to instantiate an application with a scope, then call it using the receive and send arguments:
https://github.com/django/asgiref/blob/5c249e818bd5e7acef957e236535098c3aff7b42/asgiref/server.py#L87-L94

Specification for the new Application format:
https://asgi.readthedocs.io/en/latest/specs/main.html#applications

That is: `coroutine application(scope, receive, send)`

Since the Worker in Channels is based on `StatelessServer`, this is breaking the worker functionality in Channels 3.0.0.
Is this something that is in the works? Anything I can do to help with this?

**Comment by carltongibson** [comment]
Hi @davidmarquis. 

A failing test case on Channels would be super helpful from my POV. 

Happy to push whatever back up here, if needed, but we're obviously missing coverage below stairs. 

Thanks for the input!

**Comment by lsaavedr** [comment]
Hi @carltongibson, can you try with #211 workaround, you need init the consumer:

### **after:**
```python
    'channel': ChannelNameRouter({
        'myconsumer': MyConsumer
    })
```

### **before:**
```python
    'channel': ChannelNameRouter({
        'myconsumer': MyConsumer()
    })
```

there exist a posibility to no need init the consumer?

**Comment by andrewgodwin** [comment]
Yup, this looks like an oversight on my part, sorry everyone. The PR in #211 should fix it.

**Comment by carltongibson** [comment]
Hi @davidmarquis. Can you give #211 a run to confirm whether it fixed your issue? Thanks.

**Comment by davidmarquis** [comment]
I should be able to validate this tomorrow, will keep you posted!

**Comment by davidmarquis** [comment]
Hi everyone, 

@carltongibson @andrewgodwin 

I tried with https://github.com/lsaavedr/asgiref/tree/server_compatibility (referenced in #211) and *it works*! 

But with a caveat... read on!

Initially, I was running my worker with the same config as the main application, and since the (web) app is setup to serve static files, I had an ASGI application similar to this:

``` python
application = \
    StaticFilesWrapper(
        ProtocolTypeRouter({
            'http': get_asgi_application(),
            'websocket': JWTAuthMiddleware(
                URLRouter(
                    [...redacted...]
                )
            ),
            'channel': ChannelNameRouter({
                [...redacted...]
            }),
        })
    )
``` 

Digging into this a little more, it appears `StaticFilesWrapper` is deemed a "double callable" by `is_double_callable` because it is not a coroutine / not `async`:

https://github.com/django/channels/blob/841d1700d209e493703c92c48bfa2527ce8e6180/channels/staticfiles.py#L35

``` python
    def __call__(self, scope, receive, send):
```

And thus it failed with:

```
Exception inside application: __call__() missing 2 required positional arguments: 'receive' and 'send'
  File "asgiref/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
  __call__() missing 2 required positional arguments: 'receive' and 'send'
```

Changing my worker to a simpler configuration (without the use of `StaticFilesWrapper`) worked like a charm:

``` python
worker = \
    ProtocolTypeRouter({
        'channel': ChannelNameRouter({
            [...redacted...]
        }),
    })
```

So I can validate #211 works for most cases, but using `StaticFilesWrapper` within a Channels 3.0 worker (StatelessServer) seems a no go for now. Should `StaticFilesWrapper.__call__` be changed to be an async method? I can proceed with that change and associated unit tests in Channels but would need at least a green light from someone who's able to understand the repercussions.

**Comment by carltongibson** [comment]
Hi @davidmarquis. 


I'm away from the computer right now but that sounds like a plausible analysis yes. (Static file wrapper **is** the asgi app right, so call should be async def) 

Do open a PR on channels! If you start with the test case it'll be easy to see that it's wrong. 

Thanks so much for taking the time to dig in! (I'll look back in over the weekend.)

**Comment by davidmarquis** [comment]
@carltongibson I have opened a PR for making `StaticFilesWrapper` async along with a basic test suite:

https://github.com/django/channels/pull/1567

**Comment by carltongibson** [comment]
Super. Thanks @davidmarquis!
