### ISSUE TITLE
This isn't a problem with `asgiref` - your system Python is broken. Graham comments more to this effect on the ticket you linked.

### ISSUE THREAD

**Issue by Leekyungun** [django/asgiref#212]
This isn't a problem with `asgiref` - your system Python is broken. Graham comments more to this effect on the ticket you linked.

_Originally posted by @andrewgodwin in https://github.com/django/asgiref/issues/210#issuecomment-722133611_

Hello. 

Can you tell me more about it?
Is Python installed wrong?
Or was it wrong when you installed Apache?

Thank you.

**Comment by carltongibson** [comment]
Sorry, this isn't something we can help you with further here. Good luck.
