### ISSUE TITLE
Missing changelog and git tag for 3.3.1

### ISSUE THREAD

**Issue by intgr** [django/asgiref#217]
The changelog at https://github.com/django/asgiref/blob/master/CHANGELOG.txt does not mention the new version 3.3.1 that was apparently released to PyPI on Nov 9, 2020. Nor is there a git tag.

**Comment by carltongibson** [comment]
Thanks for the report. Tagged and change notes added in ee967d2e3be77bb4c5082542a538e1c77a37a031
