### ISSUE TITLE
AsyncToSync has no attribute __self__

### ISSUE THREAD

**Issue by arm7star** [django/asgiref#222]
hi,
test_async_to_async_method_self_attribute from https://github.com/django/asgiref/pull/150/files failes on "assert sync_function.__self__ is instance". Does TestClass has attribute __self__? thank you!

**Comment by andrewgodwin** [comment]
Can you give a more detailed description of what the problem is? Maybe paste the console output and traceback so we know what you're seeing?

**Comment by arm7star** [comment]
def test_async_to_async_method_self_attribute():
    """
    Tests async_to_async on a method copies __self__.
    """
    # Define async function.
    class TestClass:
        async def test_function(self):
            await asyncio.sleep(0)
            return 45

    # Check it works right.
    instance = TestClass()
    sync_function = async_to_sync(instance.test_function)
    number = sync_function()
    assert number == 45

    # Check __self__ has been copied.
 >   assert sync_function.__self__ is instance
AddributeError: 'AsyncToSync' object has no attribute '__self__'

It seems that TestClass has no attribute '__self__' and then "self.__self__ = self.awaitable.__self__" in __init__ function of AsyncToSync class will fail.

**Comment by andrewgodwin** [comment]
I'm not sure why you're getting this error, because this test absolutely works on my local machine, and any instance of a class will have a `__self__`:

```
>>> class X:
...     def test_function(self):
...         return False
...
>>> x = X()
>>> x.test_function.__self__
<__main__.X object at 0x7f7331d18f40>
```

What version of Python are you on? Maybe it's very old or something?

**Comment by arm7star** [comment]
I'll check my environment. Maybe there are some mistakes on my environment. Thank you very much.
