### ISSUE TITLE
Can a dedicated ThreadPoolExecutor be used in SyncToAsync?

### ISSUE THREAD

**Issue by HMaker** [django/asgiref#228]
I think it's common to use the `@sync_to_async` decorator to run Django ORM's queries, but in the current setup that function will be ran in the global thread pool. I would like to set a dedicated thread pool just to run database queries, so I can keep the database connections persistent for some time. Django [states][1] the following about persistent connections:

> Since each thread maintains its own connection, your database must support at least as many simultaneous connections as you have worker threads [...]
> The development server creates a new thread for each request it handles, negating the effect of persistent connections. Don’t enable them during development.

In the global thread pool the threads may be busy running non query functions, so its persisted connection will not be usable.
I think that could be done the same way it's done for `single_thread_executor` as a class variable of `SyncToAsync`, so user's could subclasss it and change the executor. Maybe allowing it to be passed throught constructor would be better.

[1]: https://docs.djangoproject.com/en/3.1/ref/databases/#caveats

**Comment by andrewgodwin** [comment]
`sync_to_async` will always run the target function in the same thread as any other invocation of `sync_to_async` now that `thread_sensitive` defaults to `True`; would that not solve your issue? (Plus the executor only has a single thread anyway).

**Comment by HMaker** [comment]
> `sync_to_async` will always run the target function in the same thread as any other invocation of `sync_to_async` now that `thread_sensitive` defaults to `True`; would that not solve your issue? (Plus the executor only has a single thread anyway).

the `thread_sensitive` in my case is set to False since the ORM is thread-safe.

**Comment by andrewgodwin** [comment]
The whole point of `thread_sensitive` is to enable the ORM to work - threadsafe does not mean that it is not thread sensitive (that is, connections vary per thread). The feature was built almost exactly for the reason you describe - making the ORM threading and persistent connections make sense.

The only thing left to do is to make it so that thread_sensitive mode has one thread per request rather than one thread per process, but there's a series of PRs dropping that are going to enable that.

**Comment by HMaker** [comment]
So I can't have concurrent queries using persistent connections? I thought it would be OK because the `asgiref.sync_to_async` was the way, as stated in [channels docs][1], to run DB queries in an async context. In channels 2.4.0 and asgiref 3.2.10 `thread_sensitive` was by default `False`. I don't know django internals and I don't saw in any place the persistent connections are not supported in multi-threaded environments.

[1]: https://channels.readthedocs.io/en/stable/topics/databases.html#database-sync-to-async

**Comment by HMaker** [comment]
I read in other issues that it is expected a process per request, so I think currently I can't work with multi-threads in same process. Thanks for the attention.
