### ISSUE TITLE
Missing reason in close event

### ISSUE THREAD

**Issue by michallowasrzechonek-silvair** [django/asgiref#234]
If I'm not mistaken, the RFC allows applications to terminate websocket connections with optional UTF-8 encoded `reason` field: https://tools.ietf.org/html/rfc6455#section-5.5.1

At the moment doesn't seem supported by ASGI spec: https://asgi.readthedocs.io/en/latest/specs/www.html#close-send-event allows the application to set the `code`, but not the `reason`.

**Comment by andrewgodwin** [comment]
Yes, we chose not to support this because I'd almost never seen it used in the wild, and because the `code` is usually what apps want anyway rather than arbitary bytes. I'm open to adding it if there's sufficient demand.

**Comment by pgjones** [comment]
I've also been asked about this for Quart. Would you accept a PR to add it if I wrote it?

**Comment by andrewgodwin** [comment]
Yup, totally.

**Comment by michallowasrzechonek-silvair** [comment]
Thanks!
