### ISSUE TITLE
async_to_sync called inside an except block re-throws exception

### ISSUE THREAD

**Issue by devgianlu** [django/asgiref#240]
If `async_to_sync` is called inside an `except` block it will re-throw the exception thinking it's the result of the async call.

Example code:
```py
async def async_stuff():
    return 'hello'

try:
    raise ValueError()
except BaseException:
    async_to_sync(async_stuff)()
```

My workaround:
```py
async def async_stuff():
    return 'hello'

err = None
try:
    raise ValueError()
except BaseException as _err:
    err = _err

if err:
    async_to_sync(async_stuff)()
```

**Comment by andrewgodwin** [comment]
Oh yes, fun, the exception propagation logic probably needs to check if there's an exception on the way in.

**Comment by andrewgodwin** [comment]
Interestingly, I could not make this fail - I even added a test to check it: https://github.com/django/asgiref/commit/a528275e424eb31067250c14be2a88ebf797ea52

What version are you on?

**Comment by devgianlu** [comment]
@andrewgodwin I am running 3.3.1, not sure whether the fact it is running in Django with Channels affects anything. I am trying to replicate the issue as a test, but not having a lot of success. Unluckily I cannot share the code or the stacktrace because this is on a private project.

**Comment by andrewgodwin** [comment]
Interesting. It might be something else you have interacting badly (have anything else that handles exceptions or something?), but if neither of us can replicate it on a clean project I'll have to close this until we can - sorry!
