### ISSUE TITLE
Specification for Server Sent Events / SSE

### ISSUE THREAD

**Issue by srkunze** [django/asgiref#245]
Hi everyone,

not sure if this has been discussed already. I recently stumbled over SSE. https://en.wikipedia.org/wiki/Server-sent_events (coming from https://htmx.org/attributes/hx-sse/).

Right now it's hard to differentiate SSE since it identifies itself as `scope["type"] == "http"`.

Would it be possible to define `scope["type"] == "sse"`?

At least when considering Django, regular StreamingResponses are not a stable solution. async/await feels much better when coping with these kind of web requests (long living connections).

Best
Sven

**Comment by pgjones** [comment]
Hello,

I don't think ASGI need do anything special for Server Sent Events - the existing specification already supports them. [Here](https://gitlab.com/pgjones/quart/-/blob/master/examples/broadcast/broadcast.py) is an example with Quart (an ASGI Framework).

**Comment by srkunze** [comment]
Hey @pgjones thanks for your remark. I use Django and it's not really async-ready (at least from what I've seen so far). That's why I was wondering if SSE could be separated out like websockets.

The Quart example looks very concise. Is it not necessary to check for the requested `accept` header?

**Comment by pgjones** [comment]
> Is it not necessary to check for the requested accept header?

Good idea, I've added a check.

**Comment by srkunze** [comment]
It seems like everybody who wants to implement SSE needs to think about this missing check as well.

So, I am still convinced that it can be helpful also to others when SSE is standardized in ASGI in one way or another.

**Comment by abersheeran** [comment]
https://github.com/abersheeran/baize/blob/master/baize/wsgi.py#L384

In fact, you can also use SSE in WSGI applications. WSGI just doesn't support WebSocket. For HTTP, it is already very good.

**Comment by abersheeran** [comment]
By the way, I don't think it's a good idea to separate SSE. It is also just a normal HTTP response.

**Comment by srkunze** [comment]
A normal HTTP response, yes, but the connection handling is still different. Usually WSGI is not the best way here as workers are blocked and SSE are long-lived connections.

Cf.
https://stackoverflow.com/questions/21424648/http-streaming-with-apache-mod-wsgi
https://andrewbrookins.com/django/how-does-djangos-streaminghttpresponse-work-exactly/
https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.StreamingHttpResponse
https://dev.to/anoff/how-to-create-a-streaming-http-interface-in-python--ceh

**Comment by andrewgodwin** [comment]
To answer the overall idea of this issue - there's not really a sensible way we can separate SSE into a separate spec. It's literally just a different way of doing streaming HTTP responses, and as such, should live under HTTP (unlike WebSockets, which are their own binary protocol).

Could there be a nice third-party library that made composing the responses easier? Absolutely. Is this something we can help at the spec level? Not really, since that would require all servers to write and compose code just for this case - a case that's already covered with the spec anyway.
