### ISSUE TITLE
Using second sync_to_async call in a task results in deadlock.

### ISSUE THREAD

**Issue by StefanCardnell** [django/asgiref#249]
**Version**

    python 3.9.2
    asgiref 3.3.0

**Minimal Example**

```py
import asyncio
from asgiref.sync import async_to_sync, sync_to_async


def db_write():
    print("db_write()")


async def io_task():
    print("io_task()!")
    await sync_to_async(db_write)()


async def do_io_tasks():
    print("do_io_tasks()!")
    t = asyncio.create_task(io_task())
    await t
    # await asyncio.gather(io_task()) # Also deadlocks
    # await io_task() # Works


def view():
    print("view()!")
    async_to_sync(do_io_tasks)()


async def server_entry():
    await sync_to_async(view)()

asyncio.run(server_entry())
```

**Explanation**

`db_write()` is never called. My `async_to_sync`/`sync_to_async` calls are as follow:

`sync_to_async` -> `async_to_sync` -> (create task and await it) -> `sync_to_async`

Running the above results in a deadlock. Removing `create_task` and awaiting `io_task()` directly works. However in functions like `asyncio.gather` and `asyncio.shield`, tasks are created automatically and I have no control.

**Investigation**

Using debugger I can see that in the second `sync_to_async` call, `AsyncToSync.executors.current` no longer exists. This means the second `sync_to_async` awaitable gets scheduled on the executor from the first `sync_to_async` call, which has `max_workers=1`, and thus deadlocks.

Replacing `asyncio.run` with `async_to_sync` fixes the issue (but see below).

**Discussion**

This seems like a complex example, but has happened for me in the real-world as the functions represent the following things:

`server_entry()` - Asgi server (uvicorn/daphne) entry point, done by creating a new loop with `new_event_loop` (async).
`view()` - A Django rest framework View (sync).
`do_io_tasks()` - My custom async process running many network requests in parallel with `asyncio.gather` (async)
`io_task()` - A network IO task awaited by `asyncio.gather` (async).
`db_write` - My sync DB operation required after completing the IO task (sync).

[Although the django docs recommended `async_to_sync` over `asyncio.run` usage](https://docs.djangoproject.com/en/3.1/topics/async/), I don't have control over `server_entry()` and `view()` methods so the first loop is unfortunately created without `async_to_sync`. This therefore means the `sync_to_async` calls attach to a single (non-main) thread. Although I do believe all the sync code still runs in the same thread the database connections were made (`view()` in this example).

**Comment by andrewgodwin** [comment]
Ah, I suspect the use of the non-asgiref-originated `asyncio.run` is likely causing this, then. I'm not quite sure if we can make it entirely work, but I'll see if we can detect it and raise an error at minimum.

**Comment by andrewgodwin** [comment]
As a workaround, you can pass `thread_sensitive=False` to the inner `sync_to_async` call and that'll undeadlock it. The deadlock is due to the thread-sensitive executor waiting to execute on the main thread when, of course, it'll never come as asgiref wasn't involved there.

**Comment by StefanCardnell** [comment]
> Ah, I suspect the use of the non-asgiref-originated `asyncio.run` is likely causing this, then. I'm not quite sure if we can make it entirely work, but I'll see if we can detect it and raise an error at minimum.

Hi @andrewgodwin, thanks for the reply. Just to confirm, is using `async_to_sync` in the main thread to enter the loop (over `asyncio.run`) required for proper operation of `sync_to_async` calls lower down the stack with `thread_senstive=True` (the default)?

If so, I wonder what this means for environments utilising `asgiref` / `django` / `uvicorn` together. The main thread (the server process from `uvicorn`) enters the loop direct with `asyncio` and not `async_to_sync`. As `thread_sensitive=True` is now the default, enough context switching in Django views can cause this behaviour unless someone knows to swap to `thread_sensitive=False` (and `thread_sensitive=False` seems to go against the Django docs to keep all DB operations in the same thread).

Looking through `daphne` I suspect the same happens there.

**Comment by andrewgodwin** [comment]
> Just to confirm, is using `async_to_sync` in the main thread to enter the loop (over `asyncio.run`) required for proper operation of `sync_to_async` calls lower down the stack with `thread_senstive=True` (the default)?

It is not _meant_ to be, but right now it is - the code presumes it has an executor available in a higher async thread if there is one, and doesn't realise that's not always the case (e.g. if asyncio.run is used). I suspect it will not be too hard to fix with a good test case written and a big cup of tea.

**Comment by shughes-uk** [comment]
We make extensive use of this decorator in our django channels based product and sadly have run into this situation a few times, especially since upgrading to django3 and the latest asgiref where thread_sensitive is true by default.

Could it raise an exception instead of a warning? My understanding is that if `thread_sensitive` is `True` and you do it twice, there's zero chance of it ever unblocking itself.

**Comment by andrewgodwin** [comment]
If you can get a PR that detects this situation and manages to raise an exception to get out of it, that's something I'd happily merge. I suspect it's a case of putting a flag on the reuse-this-thread executor saying "I'm already being used".

**Comment by shughes-uk** [comment]
Test passing and seems to get it done https://github.com/django/asgiref/pull/263 , let me know if you need any changes
