### ISSUE TITLE
receive_many -> receive

### ISSUE THREAD

**Issue by dilyanpalauzov** [django/asgiref#25]
In asgiref/worker.py:76 replace receive_many with receive.

Likewise in django/channels.git

channels/channel.py:13:     a) Hide `receive_many` from end-users, as it is only for interface servers
channels/handler.py:132:                    _, chunk = message.channel_layer.`receive_many`(
channels/sessions.py:101:        channel, content = message.channel_layer.`receive_many`([wait_channel], block=False)
channels/test/base.py:68:        recv_channel, content = channel_layers[alias].`receive_many`([channel])
channels/test/base.py:105:        recv_channel, content = channel_layers[self.alias].`receive_many`([channel])
channels/worker.py:87:            channel, content = self.channel_layer.`receive_many`(channels, block=True)
docs/faqs.rst:137:  yourproject.asgi.channel_layer and call send() and `receive_many`()
docs/testing.rst:36:you (if you want, you can call `receive_many` on the underlying channel layer,

so that the system can be started without generating warnings.

In asgiref/base_layer.py:77 replace "intepret" with "interpret".

**Comment by andrewgodwin** [comment]
I'm in the middle of rewriting all of these so this won't be a problem.
