### ISSUE TITLE
MiddlewareSyncAsyncTests test failure on Django test suite with 3.3.2

### ISSUE THREAD

**Issue by cjerdonek** [django/asgiref#250]
I don't know if it's an issue with this project, but FYI, I see a test failure in Django's test suite that appears to have started with the 3.3.2 release:
https://djangoci.com/job/pull-requests-bionic/database=mysql,label=bionic-pr,python=python3.8/11081/

A Django ticket about it is here: https://code.djangoproject.com/ticket/32614

**Comment by felixxm** [comment]
This is an issue in test middlewares not in `asgiref`, see https://github.com/django/django/pull/14221.

**Comment by cjerdonek** [comment]
> This is an issue in test middlewares not in asgiref, see django/django#14221.

For future reference, there was an issue in `asgiref` 3.3.2. See, e.g. #251 and #253.

**Comment by andrewgodwin** [comment]
It was a conflagration of issues - `asgiref` added more strict type-checking for async functions, and the Django middleware wasn't actually marked as an async function. Thankfully both individual problems are now solved.

**Comment by felixxm** [comment]
@cjerdonek This particular issue was in test middlewares. Django on the `main` branch doesn't support Python < 3.8.

**Comment by cjerdonek** [comment]
Okay, thanks @andrewgodwin and @felixxm for confirming.
