### ISSUE TITLE
Asgiref 3.3.3 breaking change for Daphne 3.0.0

### ISSUE THREAD

**Issue by Ivo-Donchev** [django/asgiref#253]
Hi guys,
Just so you know about a problem we hit an hour ago and other people could also encounter regarding to the latest update of asgiref 3.3.3. 
Since Daphne is internally depending on `>=3.2.10`, if you re-deploy a Daphne 3.0.0 project, it'll start raising an error:
```
Exception inside application: TypeError('async_to_sync can only be applied to async functions.')
```
I opened the issue in Daphne repo - https://github.com/django/daphne/issues/363 but I'm not entirely sure whether the problem is daphne not specifying the version or a breaking change here so I decided to let you know. :slightly_smiling_face: 

Best regards,
Ivo

**Comment by yedpodtrzitko** [comment]
the issue was introduced in 3.2.2. It's discussed in #251, which was closed already

**Comment by carltongibson** [comment]
@Ivo-Donchev — I don't normally do real-time GitHub. 😀 — Can I ask you to confirm that the issue was with 3.3.2 and that it's now resolved. 

(Sorry, trying to catch up with multiple threads, whilst comments are crossing.)

**Comment by Ivo-Donchev** [comment]
Yes, I confirm that the issue was with 3.3.2 and it seems to be resolved now. I'm closing the issue here.

Thank you for the quick response again :slightly_smiling_face:

**Comment by cjerdonek** [comment]
> Yes, I confirm that the issue was with 3.3.2

You might want to retitle your issue title to reduce confusion for others. It says 3.3.3.
