### ISSUE TITLE
Bad type hints for async_to_sync and sync_to_async

### ISSUE THREAD

**Issue by adamchainz** [django/asgiref#254]
Take this example test program:

```python
import asyncio

from asgiref.sync import sync_to_async


def foo(x: int) -> None:
    print(x)


foo_async = sync_to_async(foo)


async def main() -> None:
    await foo_async(1)


asyncio.run(main())
```

On asgiref 3.3.2+ mypy complains:

```
$ mypy test.py
test.py:14: error: Incompatible types in "await" (actual type "Union[Any, SyncToAsync]", expected type "Awaitable[Any]")
test.py:14: error: Argument 1 has incompatible type "int"; expected "Callable[..., Any]"
Found 2 errors in 1 file (checked 1 source file)
```

Similar errors appear with the reverse:

```python
from asgiref.sync import async_to_sync


async def foo(x: int) -> None:
    print(x)


foo_sync = async_to_sync(foo)


def main() -> None:
    foo_sync(1)


main()
```

Pinging @graingert who added the type annotations in #233 and is generally a mypy wizard.

**Comment by FinnStutzenstein** [comment]
I have the same issue.

**Comment by graingert** [comment]
"Union[Any, SyncToAsync]" should absolutely be compatible with expected type "Awaitable[Any]"

This is generally unfixable without ParamSpec support in mypy though

**Comment by graingert** [comment]
type annotations were added here: https://github.com/django/asgiref/commit/b3257f6ca844ddb303f4d10f5dd66d86ecf43200#diff-6af8b5512d949418a62aa4e6be5c741b376f69feacf7cc5e3fe57162aaba1650R472

an `@overload` would probably help here

**Comment by andrewgodwin** [comment]
What's the best fix here? I don't want to remove the annotations but unless we can come up with something a bit more compatible I feel like we'll have to at least temporarily to stop mypy blowing up.

**Comment by adamchainz** [comment]
Should `SyncToAsync` inherit from `collections.abc.Awaitable` ?

**Comment by graingert** [comment]
You could use an alphabet soup `@overload`


```
@overload
def async_to_sync(fn: Callable[[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z], Awaitable[ZZ]]) -> Callable[[A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z], ZZ]): ...`
```
