### ISSUE TITLE
Support AsyncToSync outside of an async event loop

### ISSUE THREAD

**Issue by andrewgodwin** [django/asgiref#26]
Right now, AsyncToSync assumes it's been nested inside SyncToAsync and tries to find the outer event loop, and fails if run at the top level in sync code. It should, instead, make its own tiny event loop and run it to completion.

**Comment by laevilgenius** [comment]
I have a slight problem with current solution. When AsyncToSync is used at the top level in sync code it creates local `loop = asyncio.get_event_loop()` which points to the same loop instance as `self.main_event_loop` and is bound to the main thread. So, when `loop.close()` is called, it closes main thread's loop. As a result, after AsyncToSync call I can't use `asyncio.get_event_loop()` anymore, as it will return a closed loop, but have to use `asyncio.new_event_loop()`.

**Comment by andrewgodwin** [comment]
I have updated it to use a new event loop rather than getting the existing one, which should allow any existing event loop to be untouched (though it will only do this when the outer event loop isn't running anyway, in which case you likely would want to close it before you restart it so it's not got dangling coroutines in it)

**Comment by laevilgenius** [comment]
Another small issue. Can we actually return values from wrapped functions in both AsyncToSync (`return call_result.result()`) and SyncToAsync (`return self.func(*args, **kwargs)` in `thread_handler`)?

**Comment by andrewgodwin** [comment]
Sure - I opened a ticket for that at https://github.com/django/asgiref/issues/27
