### ISSUE TITLE
Example of inter-process ASGI servers?

### ISSUE THREAD

**Issue by oTree-org** [django/asgiref#268]
Are there any examples of people who have done inter-process communication between ASGI frameworks? For example I have an ASGI-based framework, but it's not very extensible. For example you can't add arbitrary custom URLs. It would be nice if users could just run a separate process using their ASGI framework of choice like Starlette, and my framework (which binds to the port Heroku provides) can route all requests under a certain URL namespace to that separate framework (kind of like asgi_redis/channel layer). Does this sound complicated to build?

**Comment by andrewgodwin** [comment]
I don't believe I've seen the extensibility personally - and I'm not sure you'll get a lot of people turning up here to discuss it :)

It would not be hard to build a "url routing only" ASGI app so you can mount things under certain URLs if it is *in the same process*, but external communication? We'd need some sort of lightweight server that could host the ASGI app and provide the interface for it to plug into. Which is certainly doable, but not the sort of thing we'd likely ship in `asgiref`.

**Comment by oTree-org** [comment]
OK thank you very much for the reply and explanation!
