### ISSUE TITLE
Consider using asyncio.run implementation in AsyncToSync

### ISSUE THREAD

**Issue by laevilgenius** [django/asgiref#28]
Python 3.7 introduces new `asyncio.run` function. Would be nice to backport its implementation for standalone loop in AsyncToSync. It adds an extra level of reliability by wrapping `loop.run_until_complete` with `try/finally`, cancelling pending tasks and closing async generators.
On a side note, it seems that `loop.create_task` should be preferred to `asyncio.ensure_future` in most cases, [according to Guido](https://github.com/python/asyncio/issues/477#issuecomment-268709555).

**Comment by andrewgodwin** [comment]
When Python 3.7 is released I'll come back and consider it, but we're still months away and we'd have to keep the existing implementation anyway to support 3.5. I will, however, go and crib from the implementation to make sure AsyncToSync is doing all the right cleanup.

As for `create_task`, I've moved to that here: https://github.com/django/asgiref/commit/c7e0065843a63f08a3e02970dc4bcf91f37bb153
