### ISSUE TITLE
Does the spec allow NaN and +-inf in messages?

### ISSUE THREAD

**Issue by bluetech** [django/asgiref#30]
The spec specifies that floats are allowed in messages:

> Floating point numbers (within the IEEE 754 double precision range)

From the wording alone, it implies that NaN and +inf are allowed. From what I can tell, both current channel layers (redis and ipc) use msgpack for serialization, which explicitly supports NaN and infinities. However, the most likely msgpack alternative -- JSON -- does not support these. So I think it'd be useful if the spec specified one of the following:

- Explicitly allow NaN/inf - in which case JSON implementations will need to handle them somehow. A note should be added to the spec similar to the existing "Strings and Unicode" note.

- Explicitly disallow NaN/inf - in which case msgpack implementations should reject them for parity.

**Comment by andrewgodwin** [comment]
I've made it clear in the spec - only real floats!
