### ISSUE TITLE
Why does the spec require that rejected handshakes always have an HTTP 403?

### ISSUE THREAD

**Issue by mpnowacki-reef** [django/asgiref#301]
Providing different status codes and even response bodies would be beneficial, for example when informing an app WHY user authentication failed, before the connection is upgraded to a WebSocket. What is the rationale for the requiring that HTTP 403 is returned if the server denies the connection before it is fully established (as mentioned in asgiref/specs/www.rst)? It's supposed to be a regular HTTP response, right?

**Comment by pgjones** [comment]
[Hypercorn](https://gitlab.com/pgjones/hypercorn) is an ASGI server that supports this if it interests you.
