### ISSUE TITLE
Proposal: allow optional meta key in asgi receive and send events

### ISSUE THREAD

**Issue by synodriver** [django/asgiref#302]
Some times, asgi applications may want to send some metadata to the protocol server and server may also have some metadata to send  to application in each event.

For instance, current specifications have no way to send trailer headers. However, with a meta key, like
```
await send(
            {"type": "http.response.body",
             "body": b'xxx',
             "more_body": False,
             "meta": {"headers":[(b"Test-Trailer-Header", b"abc")]}
             })
```
Then the protocol server would be able to know this body end up with traier headers. Other metadata, like http/2 priority, could also be add to the meta key. If the protocol server support meta key, it will know how to handle those metadata. Otherwise it will just ignore the meta key. 

This change are fully compatible with previous specifications versions, and those metadata can by defined by protocol servers.

**Comment by andrewgodwin** [comment]
Would this not just be covered by individual servers having custom additions to the spec themselves? What are you proposing we add to ASGI-WWW itself - just the ability to have a `meta` key in every event and in the scope that nobody cares about normally?

**Comment by synodriver** [comment]
So you mean that protocol servers implementions can have there own event definetions without caring to much about the spec if they don't break the compatibility？

**Comment by andrewgodwin** [comment]
Well, if you are implementing server-specific extensions to the spec, that's a matter for the server itself - obviously other servers won't like it, but since it's server-specific, I don't see how that would be a big problem.

**Comment by synodriver** [comment]
Thank you for your answer. Now I know what to do. I made some changes to an asgi server so it can have more control over the socket, and it can also serve normal asgi apps. I open this issue just to ensure this is allowed.
