### ISSUE TITLE
Question: value of host in client scope

### ISSUE THREAD

**Issue by WilliamDEdwards** [django/asgiref#303]
Hello!

I'm trying to get the IP address of the client in my app. I'm using Starlette and Uvicorn, an ASGI framework and server respectively.

Starlette documents the following at https://www.starlette.io/requests/:

> Client Address
> The client's remote address is exposed as a named two-tuple request.client. Either item in the tuple may be None.
> 
> The **hostname or IP address**: request.client.host
> 
> The port number from which the client is connecting: request.client.port

However, the docs at https://asgi.readthedocs.io/en/latest/specs/www.html say the following. `request.client` refers to the `WWWScope` in this case.

> client (Iterable[Unicode string, int]) – A two-item iterable of [host, port], **where host is the remote host’s IPv4 or IPv6 address**, and port is the remote port as an integer. Optional; if missing defaults to None.

I'm a bit confused here, because Starlette's docs say it could be either an IP address or a hostname, but your docs don't. Am I missing something here, or is this a Starlette documentation problem?

For future readers: `uvicorn.protocols.uvicorn.get_client_addr` and  `uvicorn.protocols.uvicorn.get_remote_addr` seem to be setting the client host and port in Uvicorn.

Apologies if this is not the right place for questions, but the note "Contribution and discussion about ASGI is welcome, and mostly happens on the asgiref GitHub repository." @ https://asgi.readthedocs.io/en/latest/index.html indicates that it is.

**Comment by andrewgodwin** [comment]
The spec says that `scope['client'][0]` is meant to be an IPv4 or IPv6 address, so that's what I would say it should be.

Obviously what actually ends up in there depends on the server (e.g. uvicorn), but the spec is pretty clear on this, and so if you're getting a hostname in there sometimes that's something happening on either the Starlette or Uvicorn end, and unfortunately not something we can really help with here!

**Comment by WilliamDEdwards** [comment]
> The spec says that `scope['client'][0]` is meant to be an IPv4 or IPv6 address, so that's what I would say it should be.
> 
> Obviously what actually ends up in there depends on the server (e.g. uvicorn), but the spec is pretty clear on this, and so if you're getting a hostname in there sometimes that's something happening on either the Starlette or Uvicorn end, and unfortunately not something we can really help with here!

Understood, just confirming there's no inner circle discussions I'm missing here that break the spec :). Thanks.
