### ISSUE TITLE
http.response.start+body

### ISSUE THREAD

**Issue by stas-dubrovskyi** [django/asgiref#305]
Hi everyone.

Separated calls like the following one add a lot of latency:

```Python
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        await send(
            {
                "type": "http.response.start",
                "status": self.status_code,
                "headers": self.raw_headers,
            }
        )
        await send({"type": "http.response.body", "body": self.body})
```

Reduce the number of calls in the chain leads to removing all useless awaits here and significantly improve performance:

```Python
    def __call__(self, scope: Scope, receive: Receive, send: Send) -> Awaitable[Any]:
        return send(
            {
                "type": "http.response.start+body",
                "status": self.status_code,
                "headers": self.raw_headers,
                "body": self.body,
            }
        )
```

Please pay ATTN

**Comment by pgjones** [comment]
I think this proposal is roughly describing a WSGI interface, which would probably be a better choice than adopting this given its wide adoption and usage.

**Comment by andrewgodwin** [comment]
I don't see what this is really gaining for the async case - if you want ultimate response performance, you probably shouldn't be using ASGI in the first place. The latency it adds should be minimal with most server implementations, too, especially if you're already handling a lot of concurrent connections.

Unless there's a good argument to take this on other than "it's slightly more efficient", I will have to say no to this one.

**Comment by stas-dubrovskyi** [comment]
Thanks for the fast response.

First of all. We don't talk about a WSGI at all. This is strictly async. But, the event loop is still a loop. Now I'm facing a situation when 95%-99% latency increases dramatically because of the long awaits chain. 

Reducing the number of awaits is good mitigation for this. For instance, an application with a chain of 15 awaits will be significantly slower than with 5 ones. The second one will release connections faster, reduce backlog size, and so on.

**Comment by stas-dubrovskyi** [comment]
Please, pay ATTN on my example. It returns awaitabe AGSI send from async function. But application still called in async way

```
app = App()
await app()
```

**Comment by stas-dubrovskyi** [comment]
Let's simplify. There is no reason for two calls of `send` in most cases. So there is should be a way to do a single call.

**Comment by stas-dubrovskyi** [comment]
@andrewgodwin In a superfast app like Falcon, the difference is about 10% in RPS.
