### ISSUE TITLE
`sync_to_async` has no effect on `timesleep`???

### ISSUE THREAD

**Issue by Jie-Yuan** [django/asgiref#309]
import asyncio
from asgiref.sync import sync_to_async

@sync_to_async
def func():
    time.sleep(1)
    

if __name__ =='__main__':
    loop = asyncio.get_event_loop()
    tasks = [func() for i in range(5)]
    loop.run_until_complete(asyncio.wait(tasks))

![image](https://user-images.githubusercontent.com/20265321/149259184-1bf4cd1d-79a0-45d1-8996-2eea6867a4f7.png)

**Comment by parity3** [comment]
10K foot view: Depending on what `sync_to_async` wrapper does, you probably need to take out the calls to func in the tasks list or wrap them in some way: `[func() for i in range(5)]` should be `[func for i in range(5)]` or similar. I can't help further because I'm a trio person, not asyncio ;)

**Comment by andrewgodwin** [comment]
`sync_to_async` defaults to thread-sensitive mode, which only allows one synchronous function to run at once (while not blocking asynchronous code). If you want to run synchronous code in parallel with other synchronous code, you need to use `@sync_to_async(thread_sensitive=False)`.
