### ISSUE TITLE
Performance regression between 3.2.10 and 3.3.0

### ISSUE THREAD

**Issue by last-partizan** [django/asgiref#316]
Hello.

After updating asgiref we found performance regression, and we traced it to this commit: https://github.com/django/asgiref/commit/7becc9daca2628c46af1cb7e46b4c47c1ea27adf

On dev instance without real load it isn't noticeable, but in production some requests has gone from ~2s, to ~12s (every few request it works ok, but then it takes 12s).

Any ideas what's happening and how it could be fixed?

My current theory is that `SyncToAsync` tries to execute something via busy executor, and it waits until some other threads are completed.

Raising ASGI_THREADS from default to 36, and it started working fine.

But, I assume, better aproach is to investigate all my `sync_to_async` calls and make them thread insensitive?

**Comment by andrewgodwin** [comment]
Yes, this was a deliberate performance regression as the previous approach was unsafe in most code. If your code is safe to run concurrently in multiple threads and does not use database connections, then feel free to go and make the relevant calls `thread_sensitive=False`.

**Comment by last-partizan** [comment]
I investigated a little further.

Actually, my code using `sync_to_async` was unrelated to this problem. And raising ASGI_THREADS does not fix this issue.

I've added some logging to sync_to_async, and added `sleep(5)` to one of my views, to simulate slow request. I'm using simple single-threaded `runserver`.

As soon as slow view is reached - every other parallel request is blocked until slow finished.

This could be solved by adding `thread_sensitive=False` to channels.http.AsgiHandler.handle.

What do you think? Should i raise this issue there?

```
 -- <function AsgiHandler.handle at 0x7f4d251a4940>, Using single_thread_executor., -- <concurrent.futures.thread.ThreadPoolExecutor object at 0x7f4d2ed81a60>

 -- <function AsgiHandler.handle at 0x7f4d251a4940>, Using single_thread_executor., -- <concurrent.futures.thread.ThreadPoolExecutor object at 0x7f4d2ed81a60>

 -- <function AsgiHandler.handle at 0x7f4d251a4940>, Using single_thread_executor., -- <concurrent.futures.thread.ThreadPoolExecutor object at 0x7f4d2ed81a60>

 -- <function AsgiHandler.handle at 0x7f4d251a4940>, Using single_thread_executor., -- <concurrent.futures.thread.ThreadPoolExecutor object at 0x7f4d2ed81a60>
```

**Comment by last-partizan** [comment]
Oh, nevermind, looks like there's already several issue for this:

- https://github.com/django/channels/issues/1722
- https://github.com/django/channels/issues/1587
