### ISSUE TITLE
Assert that there is no message to receive using ApplicationCommunicator

### ISSUE THREAD

**Issue by dgilge** [django/asgiref#32]
What do you think about having a method to assert that there is no message to receive using the `ApplicationCommunicator`?

Right now I'm doing it like this (using Channels' `WebsocketCommunicator`): 

```python
    with pytest.raises(futures.TimeoutError):
        await communicator.receive_from()
```

I'd like to have something like

```python
    assert communicator.new_messages(timeout=1) == 0
    # or maybe
    assert communicator.received_nothing(timeout=1)
```

Actually the `timeout` should be 0 by default. Otherwise the tests might take quite long if you have a lot of these checks.

**Comment by andrewgodwin** [comment]
Yes, we should probably have this - I won't be able to add it myself for a while though as I've got bugs to fix elsewhere. Feel free to submit a PR if you want.

**Comment by dgilge** [comment]
Ok, fine. What about the following? (I'm not sure about the sleep times yet. And I'd actually prefer to implement `queue_empty` simpler...)

```python
    async def queue_empty(self, timeout=0.1):
        if not self.output_queue.empty():
            return False
        if timeout <= 0.01:
            await asyncio.sleep(timeout)
            return self.output_queue.empty()
        await asyncio.sleep(0.01)
        if not self.output_queue.empty():
            return False
        await asyncio.sleep(timeout - 0.01)
        return self.output_queue.empty()

    async def queue_count(self, wait=0.1):
        await asyncio.sleep(wait)
        return self.output_queue.qsize()
```

**Comment by andrewgodwin** [comment]
I'd just have one top-level function called `communicator.receive_nothing` that raises an (assertion?) error if it _does_ receive something, that just wraps receive_from and catches the `TimeoutError`.

**Comment by dgilge** [comment]
I also thought about doing it that way. But as far as I understand the communicator is closed after this exception which is not what I want in some use cases...

**Comment by andrewgodwin** [comment]
Ah yes, the timeout will cancel it. I still thing calling it `receive_nothing` makes sense though, and implement inside that as you see fit (using queue empty detection is fine)
