### ISSUE TITLE
`sync.async_to_sync` incorrectly warns "a non-async-marked callable" for async callable class instance

### ISSUE THREAD

**Issue by flaeppe** [django/asgiref#324]
Repro

```python
from asgiref.sync import async_to_sync


class CallableClass:
    async def __call__(self):
        return None
        
async_to_sync(CallableClass())
```

Yields the `UserWarning`

```
UserWarning: async_to_sync was passed a non-async-marked callable
```

Though the code works at runtime.

**Comment by andrewgodwin** [comment]
Ah, nice catch!

**Comment by flaeppe** [comment]
Just realised that there's a corresponding check for detecting `async def` in `SyncToAsync`:

https://github.com/django/asgiref/blob/ab7379a59f9b8a43c4239553bcb35f98a83f4903/asgiref/sync.py#L359-L360

I'll open another issue/PR for that
