### ISSUE TITLE
How to call an async/sync function each with multiple functions

### ISSUE THREAD

**Issue by dineshbvadhia** [django/asgiref#330]
This not an Issue but don't know where else to ask (maybe StackOverflow?).

In a fully async program, a function `do_this() `consists of two functions `do_that()` and `do_other()`:
```
def do_this():
    def do_that()
    def do_other()
```
The function `do_this()` can be called as async or sync dependent on a flag. The sub-functions are either all async or sync and the same as the calling `do_this()`. My effort is below (note for example, the function `do_that_sync() = do_that_async()`). What is the optimal way to achieve this?
```
async def do_that_async():
    return

async def do_other_async():
    return

async def do_this_async():
    await do_that_async()
    await do_other_async()
    return

@sync_to_async
def do_that_sync():
    return

@sync_to_async
def do_other_sync():
    return

@sync_to_async
def do_this_sync():
    await do_that_sync()
    await do_other_sync()
    return

if True:
    await do_this_sync()
else:
    await do_this_async()
```

**Comment by andrewgodwin** [comment]
You can't use `await` inside a synchronous function, so your example shouldn't work. Instead, I'd probably do it more like this:

```
async def do_that_async():
    return

async def do_other_async():
    return

async def do_this_async():
    await do_that_async()
    await do_other_async()
    return

def do_that_sync():
    return

def do_other_sync():
    return

@sync_to_async
def do_this_sync():
    do_that_sync()
    do_other_sync()
    return

if True:
    await do_this_sync()
else:
    await do_this_async()
```
