### ISSUE TITLE
[possible bug] 'code' is not labeled as optional

### ISSUE THREAD

**Issue by caleb15** [django/asgiref#340]
In https://asgi.readthedocs.io/en/latest/specs/www.html#disconnect-receive-event-ws it does not say code is optional, yet it says "as per websocket spec", where [code is optional](https://datatracker.ietf.org/doc/html/rfc6455#section-7.1.5) ("**may** contain"). Later on in `Close - send event` it explicitly mentions that the code there is optional. In the first link should code be optional or required?

If code is optional I would be happy to submit a PR to this repo to update the docs.

This is not just a theoretical question, as we are facing a bug that may be related to this. In https://github.com/django/channels/blob/38324816c115567e198a573bc294d8345df5e8a9/channels/generic/websocket.py#L105 channels assumes that the `code` key exists, but in our case it doesn't exist and a KeyError is raised.

**Comment by andrewgodwin** [comment]
I believe it was intentional that it was not optional - the WebSocket spec also says:

> If this Close control frame contains no status code, _The WebSocket Connection Close Code_ is considered to be 1005

Thus, I would say servers should default that value to 1005 if it is not contained in the frame

**Comment by caleb15** [comment]
So should channels default the value to 1005, then? Or maybe Uvicorn should specify `code` ([link](https://github.com/encode/uvicorn/blob/6cf6abacd57a96c8f189fdb8d5544cd45a88f35a/uvicorn/protocols/websockets/wsproto_impl.py#L68))? Or both?

**Comment by andrewgodwin** [comment]
If I was being strict, I'd say the servers should always populate this field (so uvicorn should probably add it), but in the interests of compatibility it makes sense for channels to default it as well. I'll update the spec to clarify this, if that makes sense?

**Comment by caleb15** [comment]
Yep, that makes sense. Thanks!

**Comment by andrewgodwin** [comment]
Alright, clarified in 5118b709a04c0972bc812333b3aa92b08735dacf - thanks for highlighting this!

**Comment by Kludex** [comment]
> So should channels default the value to 1005, then? Or maybe Uvicorn should specify `code` ([link](https://github.com/encode/uvicorn/blob/6cf6abacd57a96c8f189fdb8d5544cd45a88f35a/uvicorn/protocols/websockets/wsproto_impl.py#L68))? Or both?

Uvicorn team is already aware of this. :eyes: There's a PR in WIP adding the code on those. :pray:

**Comment by andrewgodwin** [comment]
Great! Hopefully it matches the default 1005 value suggested here?

**Comment by Kludex** [comment]
Not really, and now that you've mentioned... We were actually using 1000 on some places as default, see:

https://github.com/encode/uvicorn/blob/6cf6abacd57a96c8f189fdb8d5544cd45a88f35a/uvicorn/protocols/websockets/wsproto_impl.py#L294-L304

**Comment by andrewgodwin** [comment]
Yeah, `1000` is the default for the app-initiated close, whereas `1005` is the default for the connection/client-initated close. It's... a confusing system.

**Comment by Kludex** [comment]
I see... So on the PR: https://github.com/encode/uvicorn/pull/1441/files

The first one should be 1005. Correct?

**Comment by Kludex** [comment]
Actually... Both of the ones on that PR should be 1005? 🤔

**Comment by andrewgodwin** [comment]
Yeah, both of those should be, since they are `disconnect`. `disconnect` = 1005, `close` = 1000 as defaults.

**Comment by Kludex** [comment]
Thanks Andrew :)

**Comment by carltongibson** [comment]
@caleb15 

> ...in the interests of compatibility it makes sense for channels to default it as well

If you think there's a change in Channels to be made for this, please do propose it over there. (Thanks 😉)

**Comment by caleb15** [comment]
@carltongibson, sure. I figure I might as well make the proposal a PR because the change is so easy to make: https://github.com/django/channels/pull/1905

**Comment by Kludex** [comment]
I've created a table on https://github.com/encode/uvicorn/pull/1753 about the websocket codes we should be sending back, jfyk.
