### ISSUE TITLE
sync_to_async calls hang / deadlock when called in a task

### ISSUE THREAD

**Issue by brownan** [django/asgiref#348]
I ran into a weird deadlock when writing a django async view and trying to use `asyncio.wait_for()` in conjunction with `sync_to_async` to call a sync function but timeout if it takes longer than a few seconds. Internally, `wait_for()` creates a couple of async tasks using `create_task()`. So calling `create_task()` on the return of `sync_to_async` hangs forever.

Here's a simple asgi application that reproduces the problem. I'm on asgiref 3.5.2, and I've tested this with both daphne and uvicorn. The swing between the async context and the sync context is meant to replicate the control flow used in django if you have a sync middleware in your middleware stack.

```
import asyncio

from asgiref.sync import sync_to_async, async_to_sync, ThreadSensitiveContext


def some_sync_function():
    print("Some_sync_function")


async def django_async_view():
    print("django_async_view")
    # Works:
    #await sync_to_async(some_sync_function)()

    # Doesn't work, times out:
    await asyncio.wait_for(sync_to_async(some_sync_function, thread_sensitive=True)(), timeout=5)

    # Also doesn't work, hangs forever:
    #await asyncio.create_task(sync_to_async(some_sync_function, thread_sensitive=True)())


def django_sync_middleware():
    print("django_sync_middleware")
    async_to_sync(django_async_view)()


async def application(scope, receive, send):

    # Gets a "Single thread executor already being used, would deadlock" error
    #await sync_to_async(django_sync_middleware, thread_sensitive=True)()

    # Gets an asyncio.TimeoutError:
    async with ThreadSensitiveContext():
        await sync_to_async(django_sync_middleware, thread_sensitive=True)()

    await send(
        {
            "type": "http.response.start",
            "status": 200,
            "headers": [
                (b"content-type", b"text/plain"),
            ],
        }
    )
    await send(
        {
            "type": "http.response.body",
            "body": b"Hello, world!",
        }
    )
```

Am I doing something wrong? Or is this a bug?

**Comment by andrewgodwin** [comment]
It's possible it's a bug - at the very least, if it's going to deadlock due to `thread_sensitive` it should probably raise an error rather than actually deadlocking.

When you say it "hangs forever", is it the actual create_task call that hangs, or is it that the task creates but never completes?

**Comment by brownan** [comment]
I debugged the async thread and stepped into the `create_task()` and that returned just fine. Next asyncio event loop iteration it calls into `SyncToAsync.__call__` where it gets the thread pool from the current thread sensitive context via `self.context_to_thread_executor`, an expected. The function gets submitted to the executor just fine. The executor already had a thread and so didn't need to spin up a new one. But it seems the future representing the thread executor call never returns. I'm still debugging to see if I can figure out why.

**Comment by brownan** [comment]
Actually that's not as expected, is it. The second call to `sync_to_async` should be finding the sync thread's CurrentExecutor, not the thread sensitive ThreadPoolExecutor from the context, shouldn't it?

**Comment by andrewgodwin** [comment]
Yes, if there's a nested sync_to_async call within another, it should be propagating up and using the thread of its parent so that there's no deadlock - there's a whole weird mechanism for that. I wonder the context changes caused a bug in that area somehow.

**Comment by carltongibson** [comment]
Thanks both @brownan and @jthorniley for the examples. Very nice. (@brownan this is was minimal reproduce you promised elsewhere, on the Channels issue, I suspect 😅 — I've only had a chance to read it fully.) 

I'm planning a round of Channels projects updates for this period coming up, so I'll make time to look at this too — **but** please do input if you have thoughts, as I have this in the 🤯-bucket… :) 

@jthorniley Your numbered-point description sounds quite plausible. I need to sit down and verify that. I can't respond instantly to your _"...I think the question is…"_ — I just wanted to reply to let you give you some response. (An `ACK` if you will.)

**Comment by brownan** [comment]
thanks for the analysis @jthorniley. @carltongibson I had originally thought this was a different issue than the one I reported elsewhere, but maybe not. I didn't have the time to dig into it further when I submitted that (and this) issue.

**Comment by jthorniley** [comment]
@carltongibson thanks for the quick reply. I'm sure its something that needs some examination. In the hope that it helps I've created a pull request using the change to sync_to_async as the solution - however I'm not proposing that that is necessarily the correct solution just thought it might be helpful to experiment! I've included a test that reproduces the issue when run against the current main branch.

https://github.com/django/asgiref/pull/367

**Comment by carltongibson** [comment]
In @brownan's example here we're successfully entering the `# Re-use thread executor in current context` block: 

https://github.com/django/asgiref/blob/36022636d3390c1c1cbb952336a34d652a6bfb26/asgiref/sync.py#L398-L411

... but we're not setting the `deadlock` context. 

Adding the equivalent checks to the non-context cases allows raising the _would deadlock_ error, without leading to any test failures.

**Comment by HMaker** [comment]
I have the same issue. Tried to wrap with `asyncio.wait_for()` a db query decorated by `sync_to_async()`. It hang out, but in some cases the query ran on a new thread sensitive context. The initial context, created by the django's ASGIHandler, was "bypassed". I expect all `sync_to_async()` code to run in the same thread of the sensitive context.

I think the sentive context is not being properly inherited by tasks created by `asyncio.create_task()`.

**Comment by ttys0dev** [comment]
I'm thinking the issue demonstrated in #432 may be related to this.
