### ISSUE TITLE
WebSocket disconnect event

### ISSUE THREAD

**Issue by Kludex** [django/asgiref#349]
Hi there :wave: 

I need help. :eyes: 

Let's assume that our client sent some data, the server was able to receive that data, and it's **about** to send that to the application. In the meantime, the application sent a close message.

What do I do with the data that just arrived?

Motivation comes from https://github.com/encode/uvicorn/pull/1619.

**Comment by andrewgodwin** [comment]
I mean this is a classic race condition - it depends. I'd say that it's probably more expected to not send it to the application and just drop it - while you could argue what the spec says or doesn't here, there's never a guarantee you'll receive data anyway and dropping it is much less surprising than trying to serve the application data after it's asked to close.

**Comment by Kludex** [comment]
I had the same thoughts. I'll comply with that reasoning on `uvicorn` - which is basically continuing with the current behavior.

As always, much appreciated. Thanks @andrewgodwin :pray:
