### ISSUE TITLE
Why ASGI doesn't keep track of the ws connection id?

### ISSUE THREAD

**Issue by pwtail** [django/asgiref#359]
Hi @andrewgodwin,

My impression is currently that we are missing the important info of the connection id for a ws connection. Because an ASGI-server has that info anyway since it is holding the physical connections.

We, on the other hand, should store this (send, receive) tuple ourselves, duplicating the effort. Also, our app can be run in multiple processes - then the situation gets complicated.

I actually think that send and receive can be kind of global functions, where send(ws_conn_id, msg) sends a message.

**Comment by andrewgodwin** [comment]
I don't know what you mean by the "websocket connection ID" - there's no such concept as far as I'm aware. The server might have a file handle (which can't be shared across processes), it might have an external proxy, or something else - but there's no ID that you can pass between processes to identify a socket uniquely unless you build it over the top of the base protocol.

**Comment by pwtail** [comment]
Hi! Sorry I didn't elaborate. The ID will be used to specify a connection to the ASGI server itself. Obviously it has some pointers to connection objects in memory, it could use some function of the pointer value as ID

**Comment by pwtail** [comment]
@andrewgodwin
