### ISSUE TITLE
Does the ASGI specification require asyncio?

### ISSUE THREAD

**Issue by bluetech** [django/asgiref#36]
The [specification](https://github.com/django/asgiref/blob/master/specs/asgi.rst#applications) uses the words "coroutine" and "awaitable" to describe the application callable and the `send` and `receive` parameters.

Python (the language) itself provides coroutines, but does not prescribe a way to drive them. The specification imposes one restriction: "Applications are instantiated with a connection scope, and then run in an event loop", so let's assume the application coroutine function is driven by an event loop.

Unlike other languages (Javascript, Go), Python does not prescribe a event loop driver either. Indeed, there are multiple incompatible options: asyncio, twisted, curio, trio, probably more.

The asgiref helpers, the Daphne server, and the Channels project are all built around asyncio. However, the specification doesn't require asyncio, nor does it explicitly not require asyncio. This major detail is unclear.

Following are some points regarding the two options. For the sake of discussion, let's say Django v17 will be fully async and switch from WSGI to ASGI.

### Require asyncio

- This is the status quo.
- The specification is interoperable - every server works with every application.
- Django must be written using asyncio libraries, using another (arguably better) framework like trio is not possible.
- Django can assume it is run with asyncio; for example, if it wants to sleep, it can freely do `asyncio.sleep(1)`; if it wants an async postgresql driver, it can use aiopg; etc.
- An ASGI server must run the application with asyncio; writing a server in a language other than Python is a little dubious.

### Don't require asyncio

- Servers, applications and middleware must be event loop agnostic (not really possible), or no longer be interoperable with all others.
- Servers can use the event loop that is most suitable for them, not necessarily asyncio.
- Applications can use whatever IO framework they want, not necessarily asyncio.

**Comment by andrewgodwin** [comment]
I think requiring asyncio at this point makes more sense - it has its problems, but I'm not aware of a major competitor to it that implements an alternative-and-incompatible event loop (I don't count trio as major, unfortunately).

Otherwise, we're talking about fragmenting an already-small community to a place where you have to work out what event loops you can use for the server and the application, which sounds like the thing specifications are designed to prevent. I really wish asyncio had also abstracted away the set of event-loop operations (like native sleep, socket poll etc) so event loops are more pluggable, but that is not to be.

Does that make sense to you?

**Comment by bluetech** [comment]
Yes. I think that under the circumstances in Python currently, not requiring a specific framework would destroy interoperability, which is the point of a standard after all. And that having to choose, asyncio is the most appropriate choice, since it's the status quo, it's mature, it's in the standard library, and it has many supporting libraries. I think curio/trio offer better concurrency models than asyncio, but hopefully asyncio will improve.

**Comment by andrewgodwin** [comment]
OK - I have made this explicit in the spec in 6a1912a.
