### ISSUE TITLE
Conceptual question about WebSockets codes

### ISSUE THREAD

**Issue by Kludex** [django/asgiref#364]
Hi there :wave: 

When the handshake fails, what is the ASGI server supposed to send to the ASGI application?

Since the handshake failed, `uvicorn` sends a 500 to the client, and is sending a `websocket.disconnect` with 1006 code to the application. But... That code is "fake", as I'm not sending it to the client.

What should be the expectation here? What should we send to the application?

**Comment by andrewgodwin** [comment]
1006 is the code for "we couldn't close the connection cleanly" (see https://www.rfc-editor.org/rfc/rfc6455.html) so it's the best one to use in this situation IMO!

**Comment by Kludex** [comment]
But the client is going to receive 500 status code. Is it fine? 🤔

**Comment by andrewgodwin** [comment]
Yes - the close code is not guaranteed to be what the client gets, and the spec says specifically in the case of an abnormal connection closure that 1006 is what to send.

**Comment by Kludex** [comment]
Aha. Perfect.

Thanks Andrew! 😁🙏
