### ISSUE TITLE
Does async_to_sync needs a thread per async operation? (!)

### ISSUE THREAD

**Issue by pwtail** [django/asgiref#370]
Here is my code example:

```python
import asyncio
import threading
import time
from concurrent.futures import ThreadPoolExecutor

from asgiref.sync import async_to_sync


@async_to_sync
async def my_async():
    print(threading.current_thread())
    await asyncio.sleep(3)


with ThreadPoolExecutor(max_workers=2) as exe:
    f1, f2 = (exe.submit(my_async) for _ in '12')
    [f.result() for f in (f1, f2)]
    f1, f2 = (exe.submit(my_async) for _ in '12')
    [f.result() for f in (f1, f2)]
```

The output is

```
<Thread(ThreadPoolExecutor-2_0, started 140281246127808)>
<Thread(ThreadPoolExecutor-3_0, started 140281237735104)>
<Thread(ThreadPoolExecutor-4_0, started 140281246127808)>
<Thread(ThreadPoolExecutor-5_0, started 140281237735104)>
```

So, we see that my_async keeps creating new threads. Is this OK? How to make it reuse the same thread?

**Comment by andrewgodwin** [comment]
Yes, if you just call it, it will spawn a new thread and event loop. To reuse the same thread, switch into async mode once and then use `asyncio.gather` or similar inside to run multiple coroutines.

**Comment by pwtail** [comment]
As I understand, you use async_to_sync in your takahe project. Don't you worry about it creating new threads?

**Comment by andrewgodwin** [comment]
No, as the threads are shut down once the call completes - it's not like they're building up.
