### ISSUE TITLE
Conceptual question about WebSocket Denial Response

### ISSUE THREAD

**Issue by Kludex** [django/asgiref#381]
Hi @andrewgodwin :wave: 

When the ASGI server receives a `websocket.close` message from the ASGI app before the `websocket.accept`, we (uvicorn) sends a `{"type": "websocket.disconnect", "code": 1006"}` to the ASGI app in return, and it sends an HTTP response with status code 403 to the client.

On the extension, instead of the `websocket.close` even, we'll have the `websocket.http.response.start` and `websocket.http.response.body`. I was wondering... Should the ASGI app receive the `websocket.disconnect` as well, to be analogous to what we have on the `websocket.close`? 

Ref.: https://github.com/encode/uvicorn/pull/1907/files#r1141717066

**Comment by andrewgodwin** [comment]
Yes, my interpretation of the spec is that `websocket.disconnect` should always be sent to the application when the connection is closed, no matter the reason.

**Comment by Kludex** [comment]
Once again, thanks @andrewgodwin 🙏

Hope I can meet you at PyCon US 😁

**Comment by andrewgodwin** [comment]
I'll be there!
