### ISSUE TITLE
Consider yanking version 3.7.0 from PyPI

### ISSUE THREAD

**Issue by Callum027** [django/asgiref#395]
Hi there,

We're using an old version of Django in a project, and asgiref 3.7.0 is being installed in our pipeline which enforces an older version of `typing-extensions` than is supported by it, breaking builds.

With version 3.7.1 now being released which fixes the dependency issue, please yank version 3.7.0 to ensure a broken package is not installed inappropriately.

**Comment by andrewgodwin** [comment]
Right, I didn't realise it might go and install 3.7.0 to satisfy other constraints. I have now yanked the release.
