### ISSUE TITLE
Behavior on `WebSocket.Send` on disconnection

### ISSUE THREAD

**Issue by Kludex** [django/asgiref#405]
Hi there :wave:

When I have a WebSocket application, and we don't make use of the `receive` callable, but just the `send`, and we send data on a disconnected socket, what is supposed to happen?

Currently, the behavior on Uvicorn is that we try to send the message, and since the server doesn't handle this scenario, it raises an exception that gets _leaked_ to the application.

This is the only case on ASGI that I see a server implementation detail being _leaked_ to the application without messages, so I was wondering if we should handle this case by the spec, or if it's fine to accept the current behavior.

See the code, and how to run:

```py
import asyncio

from websockets import exceptions as ex
from wsproto.utilities import LocalProtocolError


async def app(scope, receive, send):
    await send({"type": "websocket.accept"})
    try:
        while True:
            await send({"type": "websocket.send", "text": "potato"})
            await asyncio.sleep(1)
    except ex.WebSocketException:
        print("Server exception leaked to application.")
    except LocalProtocolError:
        print("Server exception leaked to application.")
```

Uvicorn has two WebSocket implementations: `wsproto` and `websockets`, you can change the implementation using the `--ws` flag e.g. `--ws wsproto` and `--ws websockets`. You can run it as:

```bash
❯ uvicorn main:app --ws wsproto
```

I use `wscat` as a CLI client:
```bash
❯ wscat -c "ws://localhost:8000/"
```

Related: https://github.com/encode/uvicorn/issues/2081

**Comment by andrewgodwin** [comment]
I'm shocked we never specified this to be honest - you'd think it would have come up before now!

I'm inclined to say that an exception is the best behaviour here, as silent failure sending things down a socket seems like a way to make people's debugging very annoying. I can think of other behaviours when this might occur, though - HTTP connections where you try to send some body after sending previous body with `more_body=False`.

Probably makes the most sense to define a common error type that gets raised in these scenarios? We could define one in `asgiref`, but that kind of irks me as it means you'd _need_ the package to implement the spec, whereas right now you don't. Maybe just saying you get something like `IOError` would be better.

**Comment by Kludex** [comment]
> I'm shocked we never specified this to be honest - you'd think it would have come up before now!

It actually came up some years ago in the FastAPI discussions. I didn't know enough by then. 😁

> HTTP connections where you try to send some body after sending previous body with `more_body=False`.

Hmm... I didn't understand this case - or how it's similar to the current.

> Probably makes the most sense to define a common error type that gets raised in these scenarios? We could define one in `asgiref`, but that kind of irks me as it means you'd need the package to implement the spec, whereas right now you don't.

This seems like it will create a barrier for package maintainers to be fully compliant with ASGI.

> Maybe just saying you get something like `IOError` would be better.

Yes, it will. But... Can we be more generic here instead? Would it be bad to write something like the following?

    The `send` event may raise an `Exception` in case the client is disconnected.

Maybe even... (to be improved)

    The ASGI framework should be in charge of catching an `Exception`.

**Comment by Kludex** [comment]
I had an idea!

What if we enable the application and the server to communicate about those scenarios beforehand?

One way could be being an ASGI extension:

```py
"scope": {
    ...
    "extensions": {
        "websockets.send.exceptions": {'exceptions': [websockets.WebSocketException, wsproto.LocalProtocolError]},
    },
}
```

API to be defined (it can be more generic, more specific), but you get the idea.

**Comment by Kludex** [comment]
Well... I see that @tomchristie created an issue here about `WebSocket.send` exceptions years ago: https://github.com/django/asgiref/issues/66. 😅

**Comment by Kludex** [comment]
- I'm going to close this in favor of #66.
