### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [django/asgiref#406]
Is it possible next time on release new version make the github release to have entry on https://github.com/django/asgiref/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by andrewgodwin** [comment]
I'll see if I can remember to do it - I should just encode releasing into an action based on a tag after all.

**Comment by Kludex** [comment]
If you want me to setup something, lmk.

**Comment by kloczek** [comment]
If you are asking for the content of the of the release entry it can be even empty entry.
Curial is create gh release entry because subject of the email notification by default contains about new release.
