### ISSUE TITLE
WsgiToAsgi doesn't send response.start on empty wsgi iterable

### ISSUE THREAD

**Issue by syntonym** [django/asgiref#41]
When the WSGI application produces an empty iterator the `http.response.start` event is never send, but a `http.response.body` event is sent. The following reproduces the issue:

```
def wsgi(environ, start_response):
    start_response("200 OK", [])
    return []

asgi = WsgiToAsgi(wsgi)
```

I think returning an empty iterable should be okay. Changing the end of `WsgiToAsgiInstance.run_wsgi_app` to the following fixed the problem for me:

```
# Close connection
if not self.response_started:
    self.response_started = True
    self.sync_send(self.response_start)
self.sync_send({"type": "http.response.body"})
```

**Comment by andrewgodwin** [comment]
Ah, whoops, looks like I missed that in testing. Do you think this is something you could open a pull request for?

**Comment by syntonym** [comment]
Sure, I just thought this is so minor you prefer to simply fix it yourself. I hope the PR fits with what you had in mind.

**Comment by andrewgodwin** [comment]
It was lovely, thanks! I am travelling at the moment so it's much easier to review pull requests :)
