### ISSUE TITLE
Add Type Annotations to `asgiref` Module

### ISSUE THREAD

**Issue by davitacols** [django/asgiref#427]
**Description:**
I propose adding type annotations to the functions in the `asgiref` module to enhance code readability and provide better tooling support.

**Changes Proposed**
- Add type annotations to function parameters and return types in the `asgiref` module.

**Benefits:**
- Improved code readability.
- Better tooling support for developers using the `asgiref` module.

**Additional Context:**
This change aims to enhance the maintainability and clarity of the `asgiref` codebase by incorporating type annotations.

**Comment by andrewgodwin** [comment]
We already have type annotations for most of the main functions, so I'm going to close this as not-a-bug; if there's specific functions that aren't typed that you think would help, feel free to open a specific issue about those.
