### ISSUE TITLE
Wording: should “extra coroutines” actually be “extra tasks”?

### ISSUE THREAD

**Issue by Hawk777** [django/asgiref#437]
In [the asyncio documentation](https://docs.python.org/3/library/asyncio-task.html), a distinction is made:
* A *coroutine function* is a function that, when called, stashes its parameters and returns a coroutine without running any of its body.
* A *coroutine* is a type of awaitable object that, when awaited, drives the body of the coroutine function forward.
* A *task* is a wrapper around an awaitable (typically a coroutine) which is registered with the event loop and causes the awaitable to be driven forward independently of other activity even when it’s not being `await`ed by some other coroutine.

[The basic specification page](https://asgi.readthedocs.io/en/latest/specs/main.html) contains many occurrences of the word “coroutine” and none of the word “task”. I believe all occurrences of “coroutine” are correct (some could be changed to “coroutine function”, but I think the meaning is clear so the extra verbosity is not necessary), *except for* the “extra coroutines” section. I could be wrong, but it looks to me like every occurrence of the word “coroutine” in that section should actually refer to tasks, not coroutines.

Thoughts?

**Comment by andrewgodwin** [comment]
No, they can be coroutines, as something in the framework or application could explicitly `await` on them periodically to drive them forward. They are relatively likely to be tasks, but they do not strictly have to be, as far as I am aware.

**Comment by Hawk777** [comment]
If they’re not a task, something has to `await` them for them to run. As far as I can tell, the only tasks that the ASGI server promises to create are one for the lifespan protocol and one for each request. If any of those things is awaiting another coroutine, then that coroutine is living within the lifetime of that other task, and so cannot be killed by the ASGI server itself (because the ASGI server doesn’t even know it exists, it only runs when the task in question drives it).

What else is there that could `await` them?

**Comment by andrewgodwin** [comment]
You can, for example, use `event_loop.call_later` in order to have something run at some future time without a Task.

**Comment by Hawk777** [comment]
Ah, I guess you could `call_later(the_coroutine.send)` or something like that (since `call_later` itself doesn’t take a coroutine but just a normal function). I guess that makes sense, though I still find the wording a little bit confusing.
