### ISSUE TITLE
Extending the WsgiToAsgi adapter, protocol routing, ASGI generics

### ISSUE THREAD

**Issue by erm** [django/asgiref#44]
Currently `WsgiToAsgi` only handles normal HTTP requests and builds sync WSGI responses. It may be useful to include a generic protocol router in `asgiref` that could be used with converted WSGI apps. The actual implementation of framework-specific details would make more sense in specific adapter implementations, but a generic protocol router that could be used with `WsgiToAsgi` could easily grant a WSGI application the benefit of ASGI async consumers without having to implement custom protocol routing for each case.

The class below modifies `WsgiToAsgi` with a dictionary mapping of protocol types to consumer handlers by path, similar to the class `ProtocolTypeRouter` in Channels.  This is just an example, but if this kind of functionality would make sense to include in `asgiref` then it may be worth further thought and discussion.

Modified `WsgiToAsgi` class:

```python
class WsgiToAsgi:

    def __init__(self, wsgi_application):
        self.wsgi_application = wsgi_application
        self.protocol_router = {"http": {}, "websocket": {}}

    def __call__(self, scope):
        protocol = scope["type"]
        path = scope["path"]
        # Check if a consumer protocol handles the request
        try:
            consumer = self.protocol_router[protocol][path]
        except KeyError:
            consumer = None
        if consumer is not None:
            return consumer(scope)
        return WsgiToAsgiInstance(self.wsgi_application, scope)

    def asgi(self, rule, protocol_type):
        """
        Route consumer handlers to the protocol router.
        """
        try:
            self.protocol_router[protocol_type]
        except KeyError:
            raise Exception("Invalid protocol type %s specified." % protocol_type)

        def _route(handler):
            self.protocol_router[protocol_type][rule] = handler
        return _route

```

Here is an example application that uses Flask:

```python
from datetime import datetime
from flask import Flask, render_template
import asyncio

wsgi_app = Flask(__name__)
app = WsgiToAsgi(wsgi_app)
app.route = wsgi_app.route

# Handled by WSGI app

@app.route("/")
def hello():
    return render_template("hello.html")

# Handled by ASGI consumers

@app.asgi("/asgi", "http")
def hello_http(scope):
    async def asgi_instance(receive, send):
        while True:
            message = await receive()
            if message["type"] == "http.request":
                await send({
                    "type": "http.response.start",
                    "status": 200,
                    "headers": [(b"cache-control", b"no-cache"),
                                (b"content-type", b"text/html"),
                                (b"transfer-encoding", b"chunked")],
                })
                await send({
                    "type": "http.response.body",
                    "body": b"Starting...",
                    "more_body": True
                })
                for i in range(5):
                    payload = "data: %s\n\n" % datetime.now().isoformat()
                    await send({
                        "type": "http.response.body",
                        "body": payload.encode(),
                        "more_body": bool(i != 5)
                    })
                    await asyncio.sleep(1)
                return
            if message["type"] == "http.disconnect":
                return
    return asgi_instance


@app.asgi("/ws", "websocket")
def hello_websocket(scope):
    async def asgi_instance(receive, send):
        while True:
            message = await receive()
            if message["type"] == "websocket.connect":
                response = {"type": "websocket.accept"}
                await send(response)
            if message["type"] == "websocket.receive":
                response = {"type": "websocket.send"}
                if "text" in message:
                    response["text"] = message["text"]
                else:
                    response["bytes"] = message["bytes"]
                await send(response)
            if message["type"] == "websocket.disconnect":
                return
    return asgi_instance

```

**Comment by erm** [comment]
I think long-term it will make sense for frameworks to implement these things themselves, but it may make it easier to encourage that type of development by providing a generic router that can demonstrate ASGI's benefits immediately. One thing I've found while creating examples is that there is a lot of commonality across the compatibility layers - the most obvious being routing consumers alongside the converted applications.

Perhaps a better approach may be something like an ASGI application that could handle routing any application that has been converted to ASGI (not just WSGI, but frameworks such as aiohttp, etc.)?

Here is an example:

```python
class ProtocolTypeRouter:

    def __init__(self, app, protocol_handlers):
        self.app = app
        self.protocol_handlers = protocol_handlers

    def __call__(self, scope):
        try:
            protocol_type = scope["type"]
        except KeyError:
            raise Exception("Connection scope missing type")
        path = scope["path"]
        try:
            handler = self.protocol_handlers[protocol_type][path]
        except KeyError:
            # Default to the converted application
            if protocol_type != "http":
                raise Exception('Unhandled protocol type "%s"' % protocol_type)
            return self.app(scope)
        return handler(scope)
```

Then `WsgiToAsgi` could be used the same way it is currently, and additional adapters that are introduced for non-WSGI apps could also use it - as an optional convenience. Here is the Flask example modified with this approach:

```python
# myapp.py

from flask import Flask, render_template


app = Flask(__name__)


@app.route("/")
def hello():
    return render_template("hello.html")


# asgi.py

from asgiref.wsgi import WsgiToAsgi
from myapp import app

wsgi_app = WsgiToAsgi(app)


# Define consumers ...

app = ProtocolTypeRouter(
    wsgi_app, {"http": {"/chunk": hello_http}, "websocket": {"/ws": hello_websocket}}
)
```

It may be useful to provide existing framework maintainers and users an easy means of running the most interesting functionality ASGI provides without taking the plunge into refactoring their existing codebases to accommodate ASGI. It could also serve as a guide to ease the process of constructing framework-specific protocol routing.

**Comment by andrewgodwin** [comment]
Well, a ProtocolTypeRouter somewhat like that is already available in Channels, but that one uses Django as the "fallback application"; even if we brought it out to be separate there'd still need to be an overridden copy that did the Django-specific part, and I suspect this is true of many other examples (URL routing varies massively).

I could maybe see adding a generic version of that into `asgiref`, but nothing much more complicated. I want to keep it as simple as possible.

**Comment by erm** [comment]
Okay, I'll implement this outside of `asgiref` for now in some examples to see how feasible a generic router implementation may be in practice, and then submit a PR later if I am able to come up with something that seems like it would be useful to include here.
