### ISSUE TITLE
Contradiction between general and HTTP-specific sections on handling of send on a closed connection

### ISSUE THREAD

**Issue by Hawk777** [django/asgiref#441]
The HTTP section of the specification was, in spec version 2.4, updated to say this:
> If `send()` is called on a closed connection the server should raise a server-specific subclass of `IOError`.

However, this appears to contradict the following text which appears in the Error Handling section of the ASGI main specification:
> Note that messages received by a server after the connection has been closed are not considered errors. In this case the `send` awaitable callable should act as a no-op.

Perhaps the main specification should say something like “unless otherwise specified by an individual protocol”?

**Comment by andrewgodwin** [comment]
Yes, it should, I'll get that update in.

**Comment by carltongibson** [comment]
Fixed by 8cf847a27da34e7d4490b41b682f657b4f302eaa
