### ISSUE TITLE
Regression in v3.8.0

### ISSUE THREAD

**Issue by carltongibson** [django/asgiref#452]
The recent 3.8.0 release causes an intermittent test failure on Django's test suite. 

https://djangoci.com/job/pull-requests-focal/database=spatialite,label=focal-pr,python=python3.11/24499/testReport/junit/asgi.tests/ASGITest/test_disconnect_with_body/

```pytb
tests % ./runtests.py asgi.tests.ASGITest.test_disconnect_with_body
Testing against Django installed in '/Users/carlton/Projects/Django/django/django' with up to 10 processes
Found 1 test(s).
System check identified no issues (0 silenced).
F
======================================================================
FAIL: test_disconnect_with_body (asgi.tests.ASGITest.test_disconnect_with_body)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/carlton/Projects/Django/asgiref/asgiref/sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File ".../asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../django/tests/asgi/tests.py", line 374, in test_disconnect_with_body
    with self.assertRaises(asyncio.TimeoutError):
AssertionError: TimeoutError not raised

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (failures=1)
```

This tests disconnect handling for a request with a body. The main task processing the request is not correctly cancelled, on some runs only. (The assertion fails, with response content `{'type': 'http.response.start', 'status': 200, 'headers': [(b'Content-Type', b'text/html; charset=utf-8'), (b'Content-Length', b'12')]}` delivered, rather than the timeout.)

Bisected to 0503c2c4df06dbe56f04689fe537325f28dbbe8b by @ttys0dev for #435. 

```
0503c2c4df06dbe56f04689fe537325f28dbbe8b is the first bad commit
commit 0503c2c4df06dbe56f04689fe537325f28dbbe8b
Author: ttys0dev <126845556+ttys0dev@users.noreply.github.com>
Date:   Fri Jan 26 23:13:55 2024 -0700

    Fix task cancellation propagation to subtasks when using sync middleware (#435)

 asgiref/sync.py    |  59 +++++++++++++++-----
 tests/test_sync.py | 159 ++++++++++++++++++++++++++++++++++++++++++++++++++++-
 2 files changed, 201 insertions(+), 17 deletions(-)
```

//cc @felixxm

**Comment by ttys0dev** [comment]
I think this may be a buggy test:
Sending a [`http.disconnect`](https://github.com/django/django/blob/5.0.3/tests/asgi/tests.py#L375) AFAIU is supposed to trigger a task cancellation exception not a [`asyncio.TimeoutError`](https://github.com/django/django/blob/5.0.3/tests/asgi/tests.py#L376).

**Comment by carltongibson** [comment]
The task is cancelled. It's the communicator that times out waiting for the response.

**Comment by ttys0dev** [comment]
> That's a regression. We need to work out why it's happened, then we can resolve it. In the meantime though, unless we can solve it quickly, I think we need to revert the problem patch and issue a 3.8.1 to avoid a breakage in deployed applications.

Debugging it now.

**Comment by carltongibson** [comment]
@ttys0dev Thanks for taking a look. 🎁

**Comment by ttys0dev** [comment]
> When the test fails — and it's intermittent so the behaviour here isn't deterministic — the main request processing task isn't cancelled, which can be checked by inspecting the output received by the application communicator.

Yeah, so it looks like the issue was that we were effectively inhibiting normal parent task `asyncio.CancelledError` propagation if the parent task was already done by the time we finished cancelling child tasks, #455 should fix that by checking if the task is done and propagating the `asyncio.CancelledError` if it was.

**Comment by carltongibson** [comment]
@ttys0dev great thanks. I will give it a run in the morning. 

Good hustle!

**Comment by carltongibson** [comment]
https://pypi.org/project/asgiref/3.8.1/
