### ISSUE TITLE
Is ASGI asyncio only?

### ISSUE THREAD

**Issue by pgjones** [django/asgiref#52]
Both [Uvicorn](https://github.com/encode/uvicorn/pull/118) and [Quart](https://gitlab.com/pgjones/quart/merge_requests/22) have recent trio support suggestions, yet I think the spec is [asyncio](https://github.com/django/asgiref/commit/6a1912aff4df6268430dae42312f4923fb2460b1#diff-d8dab7c4f9078ba87e8b91c9583f3170) based. Is there a view on this? As noted in the Uvicorn pull request if ASGI is for asyncio/trio/others then I think the servers and applications need some way to agree and hence use the same system throughout.

**Comment by davidism** [comment]
It shouldn't matter. WSGI isn't thread-based vs gevent-based, an application that wants to use gevent picks a server that supports gevent. The same should apply to ASGI.

At least in Flask it shouldn't matter at the framework level either, I don't think we do anything directly that's dependent on which implementation the server is using. It would fall to the application author to make the two match.

**Comment by pgjones** [comment]
I believe it matters for async based systems though, as noted [here](https://github.com/encode/uvicorn/pull/118#issuecomment-403223507) calling `await trio.sleep(1)` in the application won't help if the server is asyncio based.

**Comment by davidism** [comment]
Isn't that an issue with trying to get one server to support trio and asyncio at the same time? But there shouldn't be anything preventing creating a trio ASGI server. Admittedly not as cohesive as the WSGI ecosystem, where pretty much all the servers support all the worker types.

**Comment by pgjones** [comment]
I see, I misunderstood your point.

**Comment by andrewgodwin** [comment]
The ASGI spec does not necessarily require `asyncio`, though that's pretty much all the reference implementations - all it needs is an async framework that allows awaitable send/receive callables.

**Comment by andrewgodwin** [comment]
To elaborate: I think that `asyncio` should be seen as the "standard", and any server or framework that _doesn't_ support it should call that out. But I don't mind having stuff that is "ASGI-trio" as long as we don't end up in a fractured ecosystem too badly...
