### ISSUE TITLE
Documenting advised practice for ASGI task lifetime

### ISSUE THREAD

**Issue by tomchristie** [django/asgiref#65]
One of the corner areas that I think the docs ought to mention at some point is wrt. task lifetimes.

Server implementations and framework codebase ought to ensure that if they're creating sub-tasks, then main ASGI task does not finally return until all children have completed. (Similar in trio to how sub-tasks are always created within the scope of a nursery.)

This helps guard against resource leaks and ensures servers are able to perform clean shutdown/restart. (eg. servers can hard-limit the maximum number of supported concurrent tasks in order to provide better quality of service under over-resourced loads, can better monitor durations and number of any run-after-response background tasks, and can ensure clean shutdown behavior.)

This isn't something that can be enforced in the spec, but I think it's an implementation concern that's worth covering.

**Comment by andrewgodwin** [comment]
Indeed - there's honestly not much we can do in Channels at least to stop people just spinning off coroutines as there's no parenting model. When people come to me with task leaks I tend to advise them to tie their coroutines to consumer (ASGI application instance) lifetimes. Is there any better route we can advise?

**Comment by andrewgodwin** [comment]
OK, I have added this into the base spec in 9d56198 - that should at least cover the basic case. I also hope 3.8 will bring us some better options.
