### ISSUE TITLE
Cannot use async_to_sync inside sync code scheduled from an event loop

### ISSUE THREAD

**Issue by fish-face** [django/asgiref#77]
This relates to #56 in that it's requesting the same thing, but for different reasons.
I am writing a `SyncConsumer` (this cannot be changed) but need to schedule some messages to be sent at some point in the future. The most obvious way to do this is to schedule them with the existing event loop - in particular it requires no extra threads. However, the synchronous function that is scheduled still needs to call the `send` method which ultimately needs to use `async_to_sync` which throws an error.

The error is at best incorrect - it is not possible to "just await the async function directly" because this is not async code. The implicit assumption that the only reason to have a running event loop is because the code is async is wrong.

The only real workaround I can see is reaching into the Consumer internals directly and scheduling `AsyncConsumer.base_send.awaitable` (because for some reason the class replaces its own method with a version wrapped in async_to_sync if it is subclassed into a SyncConsumer...) which is too brittle.

**Comment by andrewgodwin** [comment]
I see how this might trigger the problem, but I would just avoid this by not doing that - if you need to go between sync and async this much, either do it using a list buffer and not scheduling, or write your own SyncConsumer subclass that handles this (as it already inherits from AsyncConsumer).

Sorry, but I don't think it's worth removing a safety prevention for a case where you clearly know what you're doing :) If you have a better way of solving the problem while also not allowing people to wrongly use `async_to_sync` inside an event loop, I'd like to hear it!

**Comment by fish-face** [comment]
This is not really - from the API user's point of view - going between sync and async at all. All the code I want to write is sync, but I am trying to take advantage of asyncio's ability to do scheduling. I don't really understand what you mean by "using a list buffer and not scheduling" either - scheduling is what I'm trying to achieve (the messages must be sent at specific times in the future), and a "list buffer" to me is just a list used as a buffer (I don't know of what, in this context.)

I am actually also not clear on what safety this adds. Is it literally just designed to stop people from calling async_to_sync inside async functions? If so then wouldn't getting the call stack and checking `asyncio.iscoroutinefunction` on the parent be the way to go? What if a developer's synchronous code is called from an async context (hence with an event loop) and they then need to call back to async land?

**Comment by riconnon** [comment]
@andrewgodwin I'm not sure I understand what case this is a protection against. I wonder if you could elaborate on that.

**Comment by andrewgodwin** [comment]
In the early days of Channels/ASGI, we had a _lot_ of people writing code that called async functions using `async_to_sync` inside AsyncConsumers, which of course locks up the entire event loop as it synchronously blocks the loop on an async function which needs that loop to continue before it runs.

If you can write a patch that allows `async_to_sync` in other cases but still prevents this deadlock, I will happily take it. If I remove it, though, we're going to get flooded with deadlock bug reports again.

**Comment by riconnon** [comment]
The answer may well be to provide an async scheduling helper which can be called in sync consumers so that they can safely schedule another sync method to happen later.

**Comment by andrewgodwin** [comment]
Closing due to staleness, and there apparently being no solution.
