### ISSUE TITLE
ASGI3 compatibility for ASGI2 middlewares

### ISSUE THREAD

**Issue by blueyed** [django/asgiref#82]
Could a helper similar to the one provided for apps in https://github.com/django/asgiref/pull/80 be provided?

**Comment by andrewgodwin** [comment]
It's difficult, as an explicit middleware interface was never defined in ASGI (most of them are "a callable that takes an application and returns an ASGI app", but not all), and to make it work seamlessly would require us to translate an app back into ASGI2, then run the middleware, and then translate the overall middleware back into ASGI3.

Thus, the work here is really "provide an ASGI3-to-2 converter", as with that, the rest is pretty trivial. Not sure how I feel about that yet!

Erring towards a "no" - is there a specific middleware that's going to be hard to convert to 3?

**Comment by blueyed** [comment]
It is not critical for me - I was just looking into using channel's middlewares in Starlette directly.
But I assume those get ported to ASGI3 then soon anyway.
Feel free to close it.

**Comment by andrewgodwin** [comment]
OK, no problem - thanks for the feedback!
