### ISSUE TITLE
Building the documentation

### ISSUE THREAD

**Issue by daneah** [django/asgiref#84]
In #83 I mentioned that I needed to comment out a few lines in `docs/conf.py` to get them to build. `conf.py` currently specifies both `html_theme = 'default'` and `html_sidebars = {...}`, which I believe to be mutually exclusive. The simplest thing that would fix the build is commenting out `html_sidebars`, resulting in the default sphinx theme; alternatively, setting `html_theme` to `'sphinx_rtd_theme'` and documenting the `sphinx_rtd_theme` package as a docs dependency would produce docs that look like those on https://asgi.readthedocs.io.

Earlier versions of sphinx shipped with `sphinx_rtd_theme`, but it now ships with `alabaster`. Setting the theme to `sphinx_rtd_theme` and trying to build without the dependency states:

```
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme) 
```

I can open a pull request with either solution along with a mention of the docs process in the README. Wanted to open this first to see which is preferable!

**Comment by andrewgodwin** [comment]
Let's remove `html_sidebars` and just go with the default theme. Don't think we need anything special!
