### ISSUE TITLE
Dealing with "async -> sync1 -> sync2 -> ... syncN -> async" call chains

### ISSUE THREAD

**Issue by gsakkis** [django/asgiref#94]
The following raises `RuntimeError: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.`

```
import asyncio
import sys
from asgiref.sync import async_to_sync


async def sleepy_square(n):
    await asyncio.sleep(1)
    return n*n


def sync2(n):
    return async_to_sync(sleepy_square)(n)


def sync1(n):
    return sync2(n-1) + sync2(n+1)


async def async_main():
    await asyncio.sleep(1)
    return sync1(float(sys.argv[1]))


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    print(loop.run_until_complete(async_main()))
```

As this toy example demonstrates, it's not always trivial to "just await the async function directly"; there can be multiple layers of sync functions between the top level async function and the one to be wrapped with `async_to_sync`. Is there a better alternative than having to create almost duplicate async versions of `sync1`, `sync2`, ...?

**Comment by andrewgodwin** [comment]
Your mistake is that you did not use `sync_to_async` to call `sync1` in `async_main`. If you had done that, it would be fine - as it stands, you called a "blocking" sync function in an async thread, which is not a good idea and why the library stops you doing this.

**Comment by gsakkis** [comment]
Nice, somehow it didn't occur to me you can pass back and forth the sync <-> async bridge more than once in the same call stack. Perhaps an example in the docs could point out this possibility.
