### ISSUE TITLE
Lifespan spec still uses ASGI 2 in the example

### ISSUE THREAD

**Issue by simonw** [django/asgiref#97]
Unless I'm mistaken, the example in the ASGI lifespan spec hasn't been updated to ASGI 3 yet:

https://github.com/django/asgiref/blob/095ef694972f586c96b2b83e1f7f1e8f23f4a485/specs/lifespan.rst#L19-L25

Should this be updated to ASGI 3.0 `async def __call__(self, scope, receive, send)`?

**Comment by andrewgodwin** [comment]
Fix pending review in #99.
